### ISSUE TITLE
In debug mode, add the possibility to change the debug frame height

### ISSUE THREAD

**Issue by tsteur** [matomo-org/tag-manager#1]
It would be great to show an indicator that lets users dynamically change the height of the debug iframe. Using `resize:vertical` css won't really work as the indicator is shown in the very bottom right and not is not really usable there.

**Comment by tsteur** [comment]
@AltamashShaikh this one is done by now maybe?

**Comment by AltamashShaikh** [comment]
Yes its merged, closing the issue
