### ISSUE TITLE
„Match CSS Selector“ comparison doesn’t trigger click events

### ISSUE THREAD

**Issue by bnjmngrdg** [matomo-org/tag-manager#100]
Hi there, 
when configuring a trigger with the new css selector comparison, the trigger doesn’t fire even though the console returns a positive value for the selector. Do you have an assumption, why this is happening?

Thank you and best regards!

![console_response_selector](https://user-images.githubusercontent.com/42350712/46483402-db022300-c7f7-11e8-85d5-b75109d1e973.PNG)

![trigger_css_selector](https://user-images.githubusercontent.com/42350712/46483261-83fc4e00-c7f7-11e8-8fb3-edf1efc8689c.PNG)

**Comment by tsteur** [comment]
Can you check if `MatomoTagManager.dom.bySelector("[class='logo-container']")` finds the element?

**Comment by bnjmngrdg** [comment]
Yes, it returns the output of all nodes, attributes and children of the link container.

![matomo_selector_output](https://user-images.githubusercontent.com/42350712/46520834-bd779c80-c87d-11e8-9a90-e9a8781888aa.PNG)

**Comment by bnjmngrdg** [comment]
This works, thank you! 
Am i right, that the matter will still exist, if the clicked element isn't a link container? 
An example in the following screenshots.
This trigger configuration causes, that clicks on the child-elements (like the svg image) of the button container aren't firing the event.

![tag_configuration_nolink](https://user-images.githubusercontent.com/42350712/46527604-00dc0600-c892-11e8-99c7-8b86a1d05596.PNG)

![element_container_nolink](https://user-images.githubusercontent.com/42350712/46527605-00dc0600-c892-11e8-9174-713d16e2311c.PNG)

**Comment by bnjmngrdg** [comment]
Thank you, this works for the link container. We have a similar issue with an element container whithout an a-tag. The issue is, that the trigger only fires when the exact object is clicked, yet not one of it's child-elements (like the svg logo). How can we solve this matter? Thank you very much!

![tag_configuration_nolink](https://user-images.githubusercontent.com/42350712/46528144-5664e280-c893-11e8-8774-1cce8536e39c.PNG)
![element_container_nolink](https://user-images.githubusercontent.com/42350712/46528145-5664e280-c893-11e8-9100-921429b9ab6d.PNG)

**Comment by tsteur** [comment]
I wonder if in this case the selector would need to be like `.main-nav-toggle *`? This wouldn't include the `.main-nav-toggle` element itself though.

**Comment by tsteur** [comment]
Just tested the `*` version and this should work

**Comment by tsteur** [comment]
Don't know if this affects this feature? BTW we are not using jQuery but the browser native `querySelectorAll`: https://developer.mozilla.org/en-US/docs/Web/API/Document/querySelectorAll

**Comment by bnjmngrdg** [comment]
I'm not sure aswell in this one. For the querySelector there seem to be similar problems: 

https://stackoverflow.com/questions/23034283/is-it-possible-to-use-htmls-queryselector-to-select-by-xlink-attribute-in-an

https://github.com/jsdom/jsdom/issues/2028

I'm going to look a little deeper into those issues...

**Comment by X-Coder** [comment]
I run into similar issue with this, when the classnames of the element I want to select using the css selector contains other classnames (which could change over time).

Just a simple example, I want to select it by css selector using class name my-element:
```
<a class="btn btn-circle my-element"></a>
```
Take a look at this code from tagmanager.js (especially last line):
```
                        case 'match_css_selector':
                            if (!expectedValue || !actualValue) {
                                return false;
                            }
                            var nodes = DOM.bySelector(expectedValue)
                            return utils.indexOfArray(nodes, actualValue) !== -1;
```
Why are you selecting the elements using DOM.bySelector (which is the right way until here) and right after this selection, compare the already selected element class names again by the full actualValue (classname) of the original element? -with this, filtering by css selectors is kind of pointless and can't work? -This works only if the class name matches exactly.

**Comment by tsteur** [comment]
@X-Coder 

> compare the already selected element class names again by the full actualValue (classname) of the original element

It should compare the actual element whether it is in the list of nodes, not the element class name.

**Comment by X-Coder** [comment]
For me actualValue contains all the class names of the element as string, and not the element itself, as you say.

This is chrome console debug output:
```
utils.indexOfArray(nodes, actualValue)
-1

nodes
Array [ a.btn.btn-circle.my-element ]

actualValue
"btn btn-circle my-element"
```

**Comment by tsteur** [comment]
Unfortunately, for this selector you must provide an HTML element to the trigger condition. Meaning it only works on elements. If you have a css class, you can maybe use the contains or equals selector.

**Comment by X-Coder** [comment]
Thank you, had just same thought, at the same time :)

This was my fault. I should have used the condition "Element-Klick" instead of "Klick Klassen".

**Comment by saburlimbur** [comment]
Thanks bruhh
