### ISSUE TITLE
Update button remains disabled during some actions

### ISSUE THREAD

**Issue by scysys** [matomo-org/tag-manager#105]
Reproduce

- Open an Tag
- Click on the little remove Icon to remove an item under "Don't execute this tag when any of these triggers have been triggered."

Now the update button remains disabled.

![bildschirmfoto 2018-10-05 um 19 42 08](https://user-images.githubusercontent.com/1695531/46551046-fe4fcf80-c8d6-11e8-824f-94c65990aefa.png)

**Comment by tsteur** [comment]
Cheers for reporting it 👍
