### ISSUE TITLE
Creating Matomo Analytics Tag fails

### ISSUE THREAD

**Issue by tomper00** [matomo-org/tag-manager#11]
When I try to create a Tag of the type Matomo Analytics, I am trying to use the dropdown to select my existing Matomo configuration(Assign a Matomo configuration), but the list is empty. (I have 2 sites configured, so there should be a result.) I even restarted my servers to try to remove the possibility of a caching issue.

**Comment by tsteur** [comment]
Can you maybe post a screenshot? You may need to "Create a Matomo Configuration" first. For new sites we create a Matomo Configuration automatically, but we don't do it yet for existing sites. We might change this behaviour though.

**Comment by tomper00** [comment]
I think I misunderstood how this is working.
I expected the interface to automatically list my Matomo websites on this server, but it makes sense to have a configuration object in between since your Matomo site might be on another server.

**Comment by tomper00** [comment]
Closing this
