### ISSUE TITLE
Bug: Changing name of variable causes removing trigger in a tag

### ISSUE THREAD

**Issue by ben-dw** [matomo-org/tag-manager#110]
If you use a variable in a tag, eg "const.enviroment" and you rename to "environment" the trigger will be removed.

![image](https://user-images.githubusercontent.com/43407231/46618016-ae634980-cb1e-11e8-882a-0e29f0f71ad7.png)

**Comment by tsteur** [comment]
Where exactly is the trigger removed? Can you maybe explain the steps to reproduce this?

When you rename a variable, it shouldn't remove anything but update the variable name on all references in tags and triggers in https://github.com/matomo-org/tag-manager/blob/master/Model/Variable.php#L223-L260

**Comment by ben-dw** [comment]
It doesn't matter which tag you use, as I have tested several.
eg. Honeybadger - I have used a variable called "const.environment". The trigger was set up to "All pages".
I had to change the variable name to "environment". Checking the tags, the variable was updated, but the trigger was removed from the tag. The trigger itself still exists.

**Comment by tsteur** [comment]
Cheers 👍  working on a fix right now
