### ISSUE TITLE
Cross domain tracking is not working

### ISSUE THREAD

**Issue by NanorPiwik** [matomo-org/tag-manager#118]
Hi,
I tested the cross domain tracking through Matomo Tag Manager by following this guide https://matomo.org/faq/how-to/faq_23654/ and it does not work. I tested it without Matomo Tag Manager and it worked straight away.

**Comment by tsteur** [comment]
That's likely because we'll need to expose `setDomains` to the Matomo Config I suppose.

**Comment by tsteur** [comment]
Now that https://github.com/matomo-org/tag-manager/pull/177 is merged, this feature should work when the domains are configured.
