### ISSUE TITLE
Question: Supporting Custom Variables

### ISSUE THREAD

**Issue by Paradinight** [matomo-org/tag-manager#128]
Hello Matom Team,
i have a little question: Is it possible to support custom variable?

**Comment by tsteur** [comment]
It's not planned as we will be deprecating custom variables eventually. It could be added still but there's some problem that the form fields needed for this is currently not yet implemented in core. (you would need 4 fields per row/custom variable, core currently allows only up to 2 fields per row).

**Comment by Chardonneaur** [comment]
Hi there,
do you have any updates dealing with this feature? A client of mine has already Matomo Tag Manager set on all the website and need a multiple value for page type, which correspond exactly to what custom variables can do.
From my understanding, this is a template change within the Matomo variable configuration.
What I don't know is how hard it is to make this change?

**Comment by mattab** [comment]
unfortunately we may not have time to implement Custom Variables in Tag manager.
We recommend using Custom Dimensions instead of Custom variables: https://matomo.org/guide/reporting-tools/custom-dimensions/

**Comment by mattab** [comment]
We would accept pull requests for it, so re-opening
