### ISSUE TITLE
Event Value: "The value is not a number" when using variable

### ISSUE THREAD

**Issue by jrpub** [matomo-org/tag-manager#130]
Hi,

Sorry if this issue is not a bug. When I try to set a variable name as the value of an event in the tag manager, I have the error message: 

`Event Value: The value is not a number.`

I tried with several variables (custom - for instance a constant - or a predefined one). Is this not supported or did I miss something? The weird thing is that there is the variable selector button near the "Event value", so I guess this is a supported feature.

```
Matomo version: 3.7.0
MySQL version: 5.7.24-0ubuntu0.18.04.1
PHP version: 7.0.32-0ubuntu0.16.04.1
```

**Comment by tsteur** [comment]
👍  done

**Comment by jrpub** [comment]
Tested, it works to validate the form, but however I don't understand something.

- My current event value is: {{ScrollVerticalPercentage}} (which is a native variable).
- Once I save that, the form shows "0" (meaning that the variable is likely replaced immediately). 

I expected the same behaviour as if I put  {{ScrollVerticalPercentage}} in "Event actions", where the variable is replaced on the tracked website not in Matomo.

**Comment by tsteur** [comment]
> Once I save that, the form shows "0" (meaning that the variable is likely replaced immediately).

Where is it replaced immediately? In the create/edit form it still shows the variable name for me.

**Comment by jrpub** [comment]
The eventValue is correctly sent to the API: 

![screenshot_2018-11-25_20-31-57](https://user-images.githubusercontent.com/26855134/48983611-475f1b80-f0f1-11e8-96a0-800a127e311e.png)

**Comment by tsteur** [comment]
Sorry about that, I just noticed I've only applied part of the patch and not all my changes I had. Fixed it in https://github.com/matomo-org/tag-manager/commit/478e05718cb33c13f23d70d9409bbbbb4c67c88b

**Comment by jrpub** [comment]
Ah yes, much better! It works. 

I can stop to debuging it myself :p 

Many thanks!

**Comment by jrpub** [comment]
Not fully solved yet! 

"The event value can only include numeric values and variables." when publishing the new tags.

**Comment by tsteur** [comment]
So sorry about that! See fix in https://github.com/matomo-org/tag-manager/pull/131 . Was very early this morning and must have forgotten to look at the tests (which I usually always do). Should be fixed now but will wait for tests to pass before merging.
