### ISSUE TITLE
Variable for Matomo idSite not working

### ISSUE THREAD

**Issue by alpening** [matomo-org/tag-manager#133]
I tried to follow the step to create a varibale with the siteID based on hostname and lookup table as written in the docs (https://matomo.org/docs/tag-manager/#advanced-variables-settings-default-value-lookup-table)

But when I try to save the Matomo Configuration, I always get this error message: `Matomo idSite: An unexpected website was found in the request: website id was set to '0' `

Im using Matomo 3.7.0 and TagManger 0.2.6

Do I miss something important, or is this a bug?

**Comment by tsteur** [comment]
that's a bug, will create a PR 👍
