### ISSUE TITLE
Manage Containers Tab is Empty

### ISSUE THREAD

**Issue by andiadiprasetyo** [matomo-org/tag-manager#140]
Hi,

I just updated Matomo to v.3.7.0 and just knew that Matomo now have their own Tag Manager, but when I tried to set up the container, it's just showing empty page (see screenshot).

Can anybody help me with this? Is there something wrong with my instalation

![image](https://user-images.githubusercontent.com/25949476/49709611-daf32900-fc67-11e8-9cd7-554328837b5e.png)

**Comment by tsteur** [comment]
Is this still happening? Are you familiar with the browser console? Do you see any error logs in there?

Or do you have access to your server? Maybe for some reason the JavaScript files couldn't be deleted or so. Maybe you could go into your Matomo directory and execute `./console cache:clear`?

**Comment by andiadiprasetyo** [comment]
@tsteur it's fixed now. I just cleared my browser cache and it's working. Probably just a cache problem with my browser. Thanks anyway

**Comment by tsteur** [comment]
Thanks for letting us know 👍
