### ISSUE TITLE
TypeError: I is null

### ISSUE THREAD

**Issue by xull** [matomo-org/tag-manager#153]
I'm trying to put a container on my website, and I can't seem to get this error to go away.

![error](https://user-images.githubusercontent.com/2718611/52221487-e1b4ab80-2866-11e9-8f42-d4d89b74a10b.png)

**Comment by tsteur** [comment]
Moved this issue to the tag manager repository... can you send us the URL to the container? Or the container file itself? Or export the container?

For some reason it seems like `document.body` is null. If you could send us a link where you have the container embedded that would be great. Feel free to send it to us by email to hello at matomo.org if you don't want the link to be public.

**Comment by xull** [comment]
Okay, I emailed it

**Comment by tsteur** [comment]
Thanks, replying there :)

**Comment by xull** [comment]
The issue was solved by placing the script for the container at the bottom of the page.

**Comment by tsteur** [comment]
cheers for letting us know 👍
