### ISSUE TITLE
Tag manager requires write access. Is there an alternative solution?

### ISSUE THREAD

**Issue by MoralCode** [matomo-org/tag-manager#154]
As instructed by my hosting provider, I have not allowed Matomo to write files to anywhere but a tmp folder for security reasons. However, I am unable to publish versions through tag manager because my Matomo instance complains about being unable to write to a folder, which I do not want to allow.

I notice that in the tag manager code snippet, it is trying to access a file `js/container_[my container id].js` on my Matomo instance. I presume this is the only thing that it needs to write to the directory, so I was wondering if there could be an option to download that file and manually upload it for people who run their own Matomo instance and want to keep their Matomo instanced extra-secure by not allowing the user that runs the web code to write files.

**Comment by tsteur** [comment]
@MoralCode re download feature see https://github.com/matomo-org/tag-manager/issues/7

As for the writable.... you can configure the location in your `config/config.php` file. Likely this file doesn't exist and needs to be created. You can configure it like this:

```php

return array(
    'TagManagerContainerStorageDir' => function () {
        // the location where we store the generated javascript or json container files
        return '/js';
    },
    'TagManagerContainerWebDir' => function (\Psr\Container\ContainerInterface $c) {
        // the path under which the containers are available through the web. this may be different to the storage
        // path if using eg htaccess rewrites
        return '/js'
    },
);
```

you could point the storage to the tmp folder for example and then download the files from there. I haven't tested but you could potentially even point the path to a directory outside the matomo directory like `/../tagmanager`

**Comment by MoralCode** [comment]
@tsteur I was able to make it work as you suggested by setting the `TagManagerContainerStorageDir` to `/../tmp`, however, because the config file is located in the plugin's `config` directory, it gets overwritten anytime I update matomo. Is there a way to set this configuration option in matomo's global `config.ini.php` file?

**Comment by tsteur** [comment]
you should locate the file in `$matomoroot/config/config.php` and the file will not be replaced when updating.

**Comment by MoralCode** [comment]
@tsteur do i have to link to it from the `$matomoroot/plugns/TagManager/config/config.php` file? or is there a specific path/filename that TagManager looks for inside the matomo configuration directory?

**Comment by tsteur** [comment]
it's an absolute path within the Matomo directory. You could use `/../..` though as well. It's just important they are still served through the web in case you want to embed them into your website directly.
