### ISSUE TITLE
MatomoTag loadTemplate piwik fallback looks broken

### ISSUE THREAD

**Issue by danimoh** [matomo-org/tag-manager#156]
Just by skimming though the code, the following line looks odd:
https://github.com/matomo-org/tag-manager/blob/55106e4dbeffe52196f75fa9618321fd5a070c7c/Template/Tag/MatomoTag.php#L156

The `piwik.js` fallback in line 157 will never be executed.
Should the `elseif` rather be a normal `if` such that this line executes when `@file_get_contents(PIWIK_DOCUMENT_ROOT . '/matomo.js')` failed?

See https://github.com/matomo-org/tag-manager/pull/157

**Comment by tsteur** [comment]
Good fine 👍
