### ISSUE TITLE
File integrity check failed on Matomo 3.11.0

### ISSUE THREAD

**Issue by toredash** [matomo-org/tag-manager#174]
When running on Matomo 3.11.0, the systemCheckPage wrongly informs the user that it should delete the tracker.php file in tag-manager:

> Files were found in your Matomo, but we didn't expect them.
> --> Please delete these files to prevent errors. <--
> 
> File to delete: plugins/TagManager/config/tracker.php

I would open a PR for fixing it but I was unable to figure out where the code for this is.

**Comment by tsteur** [comment]
Not seeing this on our installation. Did you create the file manually?

**Comment by toredash** [comment]
Yes, I add this file to improve performance as noted here: https://github.com/matomo-org/matomo/issues/14420

**Comment by tsteur** [comment]
@mattab @Findus23  any thoughts on this? Would have expected this to be in the manifest file?

**Comment by mattab** [comment]
would maybe work to add `tracker.php` to https://github.com/matomo-org/matomo/blob/00d15def20e9654d5855326012099a0c8654e3cb/config/global.php#L101 - @toredash feel free to test and open a PR if possible :+1:

**Comment by toredash** [comment]
@mattab Thanks for the help!

PR added here: https://github.com/matomo-org/matomo/pull/14747
