### ISSUE TITLE
Matomo scalability / usability

### ISSUE THREAD

**Issue by rmersie** [matomo-org/tag-manager#180]
Hi Matomo,

We've recently installed Matomo into the SaaS version of our product and are actively monitoring 30 - 50 webshops using Matomo and this number will continue to grow in the future. During the process of installing / configuring Matomo, we ran into some 'usability issues'. I'd like to share these with you and would like to know if there would be any solutions you know of to make (mainly) maintenance easier.

Case: For each customer that we add on SaaS, we have defined two flows:

1. Installation flow: create site (in Matomo), create tag container, configure the site + container, publish the container, get the container ID and add it to the web.config of the customers SaaS instance.

2. Tag Container maintenance flow: if we want to measure specific data, we can create tags / variables in the Tag Container for this. Right now, we need to either add these tags per store manually OR export the container of one store that we changed and import it into the other containers.

Obviously, when you need to do this for a lot of stores (as we do), these tasks become repetative and ideally you'd want to automate this. Since it's a SaaS product, we're sure that each customers store is the same (configurations might be different, but the codebase is identical). We therefore configure Matomo identically per customer. Automating the installation flow seems doable, but for the tag container maintenance, we found that variables contain an idSite which makes exporting and importing Tag Container 'templates' a bit more cumbersome: we need to generate the template, then get the siteID per container, swap the idSite in the variables of the Tag Container and then import it into the specific Container, and then as a last step create a new container version and publish the container.

My question: is there a (Matomo) solution to automate this / make this easier?

Best regards,
Ronald

**Comment by tsteur** [comment]
Hi @rmersie 

You can either use the API and automate everything see https://developer.matomo.org/api-reference/reporting-api#TagManager

Or you could read the idSite from a DataLayer variable and put something like this in the website to configure the idSite: `_mtm.push({'matomoIdSite': XYZ})`. Then you would maybe need only one container for them all.

If you have other questions feel free to ask in the forum https://forum.matomo.org or check out our support plans https://matomo.org/support-plans/

We usually don't answer questions here.
