### ISSUE TITLE
Question: tag-manager (container_xxx.js) in distributed Matomo deployments

### ISSUE THREAD

**Issue by robertgstoehl** [matomo-org/tag-manager#181]
In distributed deployments like 2x tracker behind loadbalancer, webui separeted eg: https://matomo.org/faq/new-to-piwik/faq_134/

how does one keep the generated (and changing) container javascript files in sync? As of now I assume shared storage or file based replication would solve this (but would prefer if this would be handled transparently within Matomo itself ;) )

Thoughts on this?

**Comment by tsteur** [comment]
@robertgstoehl best to ask this in forum.

Created this issue a while ago https://github.com/matomo-org/tag-manager/issues/81 to fix it through a CDN.

An alternative be to have `js` folder of Matomo a network folder like EFS or NFS. If you're familiar with PHP, you can [write a plugin](https://developer.matomo.org) that is listening to the event `TagManager.containerFileChanged` like this `function ($updatedFilePath) {  uploadToCdnOrS3OrSyncFileWithOtherServers($updatedFilePath) }`. 

Another less ideal way be to eg run `./console tagmanager:regenerate-released-containers` every X minutes to regenerate the files if they changed
