### ISSUE TITLE
Tag Manager Preview UI tries to encode circular structure as JSON

### ISSUE THREAD

**Issue by danimoh** [matomo-org/tag-manager#185]
Hello,
If the preview UI tries to display a data structure with a circular structure it fails at JSON encoding, an uncaught exception gets thrown and the UI doesn't update.

This can happen for example in the following setting:
- define an `AllElementsClick` trigger
- open the tracked website in debug / preview mode
- give an element on the page a reference to itself, e.g. `el.selfref = el;`
- click that element
- `mtm.clickElement` will be pushed to the datalayer
- And here is what I assume is happening: the preview UI tries to JSON encode the datalayer to display it and fails due to the circular structure caused by the self reference.

Of course the given example is a bit silly, however for example when a UI framework that binds a circular structure to the element is used this becomes an issue.
For instance, vue binds a `__vue__` property to the root element of a component from which a circular structure is given via `__vue__.$el`.

**Comment by tsteur** [comment]
To avoid this, we would need to have some custom method I suppose that checks if an element is a DOM element or something like this in https://github.com/matomo-org/tag-manager/blob/master/javascripts/tagmanager.js#L43 :

```
JSON.stringify(arguments[i], function( key, value) {
  if(value instanceof HTMLElement) { 
    return value.nodeType;
  } else {
    return value;
  };
});
```

I haven't tested it though. @danimoh  any chance you could update your Matomo Tag Manager with this JavaScript code: https://github.com/matomo-org/tag-manager/pull/186/files

and then wait for an hour for the JS files to be updated and / or call `./console tagmanager:regenerate-released-containers ` to regenerate the containers?

**Comment by mattab** [comment]
Hi @danimoh Would you be able to test the patch and confirm if it fixes the issue for you? https://github.com/matomo-org/tag-manager/pull/186/files Be great to hear from you and merge this PR eventually.
