### ISSUE TITLE
Add a system check that detects WAFs

### ISSUE THREAD

**Issue by Findus23** [matomo-org/tag-manager#187]
Multiple people have reported issues with tag manager caused by web application firewalls.
Many are blocking form submission when the POST data contains HTML.

I'd propose adding a system check that trie sending POST data with HTML in it and checks for a 403.

See also https://stackoverflow.com/questions/57843666/saving-custom-scripts-in-matomo-tag-manager-results-in-403/57844903#57844903
https://forum.matomo.org/t/benutzerdefiniertes-html-im-tag-manager/33535
https://forum.matomo.org/t/custom-html-not-saving/32927/5

**Comment by Findus23** [comment]
See also https://github.com/matomo-org/matomo/issues/3371 for a more general mod_security detection (which might be harder to do reliably than this specific rule).

**Comment by AltamashShaikh** [comment]
Closing this as we are not fixing this in core
