### ISSUE TITLE
Is it possible to implement and manage cookies and privacy status with the tag manager?

### ISSUE THREAD

**Issue by mannp** [matomo-org/tag-manager#19]
Thanks for the tag manager it looks like a great addition, but I am not fully sure what I will use it for as yet, but I am sure that will become clear with time.

I wondered -> Is it possible to implement and manage cookies and privacy status with the tag manager?

Thanks in advance

**Comment by mannp** [comment]
Thanks @tsteur thats exactly what I meant, all of the above.

Is there a working snippet within the tag manager so I could understand how to show a privacy notice as a start and i could then try and incorporate the js code already published from matomo to enable opt in and out at all?

**Comment by tsteur** [comment]
There is actually an example here: https://developer.matomo.org/guides/tagmanager/custom-tag as part of the custom tag guide :) 
And also here: https://developer.matomo.org/guides/tracking-javascript-guide#asking-for-consent and / or here: https://developer.matomo.org/guides/tracking-javascript-guide#optional-creating-a-custom-opt-out-form

**Comment by mannp** [comment]
Thanks, I have seen all of those links and none of them give an example for the tag manager, but instead snippets of disperate code.

I will eventually understand them and how to put them together into a workable solution.
