### ISSUE TITLE
How to track user id dynamically?

### ISSUE THREAD

**Issue by senthilaim** [matomo-org/tag-manager#195]
Hi Team,

Tag manager is very great. I need yours help for track user id dynamically. 

![useid](https://user-images.githubusercontent.com/46022329/67359302-8a837200-f580-11e9-9758-0dd72942cc09.PNG)

I am using angular 7 framework. If i set static username is working well. But i want to set username dynamically. I would appreciate your help to resolve this issue.

Let me know if need more clarification.

Thanks,
Senthil.

**Comment by tsteur** [comment]
Hi there, questions be best asked in the forum: https://forum.matomo.org

You can basically create a data layer variable named say "MatomoUserId" and you can then assign this variable to the userId in the screenshot like `{{ MatomoUserId }}` (or use the picker on the right) in the User ID field.

You can then push the userId to the data layer see https://developer.matomo.org/guides/tagmanager/datalayer

**Comment by senthilaim** [comment]
Thanks @tsteur

**Comment by vickram10** [comment]
hi, understood the configuration part in  data layer i configured it..but index page i am doing some error can you please share me a example to script in index page ...thanks
