### ISSUE TITLE
When in debugging mode, delete the debugger parameter from being passed to the TagManager

### ISSUE THREAD

**Issue by peterbo** [matomo-org/tag-manager#200]
In my use case, I have a Regex running against the PageUrl ((en|fr|pt|cz|ru|jp|es)(?:\/)?(?:\/index\.jsp)?$). This won't work, if the PageURL contains the mtmPreviewMode=xxx parameter. So I had to change the Regex to (en|fr|pt|cz|ru|jp|es)(?:\/)?(?:\/index\.jsp)?(?:\?mtmPreviewMode\=XXXXXX)?$ to make it work. The most elegant solution would be to hide the preview parameter from the internal TagManager variables.

**Comment by tsteur** [comment]
Indeed. The PageURL defined in https://github.com/matomo-org/tag-manager/blob/0.2.6/Template/Variable/PreConfigured/PageUrlVariable.php should ideally remove this parameter if it is present.

**Comment by AltamashShaikh** [comment]
@peterbo It should be fixed with https://github.com/matomo-org/tag-manager/issues/217
