### ISSUE TITLE
Add some statistical reports

### ISSUE THREAD

**Issue by scysys** [matomo-org/tag-manager#21]
First, this is an absolutely great enhancement to Matomo!

As I can say at this moment, I don't have any Problems with the Tag Manager.

What I missing are some statistical reports like:

- tag loads
- tag loads over the past x days

and so on.

**Comment by scysys** [comment]
I don´t see there is already the same question: https://github.com/matomo-org/tag-manager/issues/3

**Comment by tsteur** [comment]
I'll close it in favor of #3
