### ISSUE TITLE
Update version of Tag Manager script

### ISSUE THREAD

**Issue by Laul0** [matomo-org/tag-manager#211]
# Summary

During the tests and developments, use the latest version in Preview mode or Dev is essential.

## Current behavior

1. Edit the current version (Live) of the Tag Manager
2. Create a new version Dev
3. Change URL on the target Web site **OR** enable Preview mode

The used version still the previous one.

Here, a screenshot of the new version in preview mode:
<img width="820" alt="Screen Shot 2020-01-06 at 16 52 21" src="https://user-images.githubusercontent.com/15279205/71851713-219e9700-30a5-11ea-86f5-7bb7442544e0.png">

Now, the result from the website:

<img width="847" alt="Screen Shot 2020-01-06 at 16 54 42" src="https://user-images.githubusercontent.com/15279205/71851859-7d692000-30a5-11ea-882a-e9bcac3a8cf4.png">

## Expected behavior

Each time a new version is released or preview mode enabled after some modifications, the latest version of the script should be executed.

**Comment by tsteur** [comment]
Just checking: By any chance do you maybe have a multi server environment set up?

**Comment by Laul0** [comment]
Nop. Only one Docker matomo server.
