### ISSUE TITLE
Error when create a new version

### ISSUE THREAD

**Issue by Laul0** [matomo-org/tag-manager#213]
## Summary

After a couple of modification, a new version have to be create.

### Current behavior

After a couple of modification, a new version have to be created but after clicking on the create new version and publish, the following error message appear:

<img width="1686" alt="Screen Shot 2020-01-07 at 23 13 24" src="https://user-images.githubusercontent.com/15279205/72197790-6868f580-33f3-11ea-89e5-bfd34f9699ca.png">

The version seems create correctly (not 100% sure) but the version is not published.

It is possible to publish the new version created again with no error but the behavior of the release is not the same than the preview.

This behavior can be reproduce each time

### Expected behavior

1. Perform some modification
2. Publish a new version
    * specify the version name
    * specify the environment
3. Click on `CREATE A NEW VERSION AND PUBLISH RELEASE`

Result: the new version is created with no error.

**Comment by tsteur** [comment]
@Laul0 I can't reproduce this here. Are you using the latest version of Matomo? 

Considering you also have issue with https://github.com/matomo-org/tag-manager/issues/211 there seems to be something not quite right with your server set up. Maybe you can tell us more about your set up or maybe even give us access to it?

**Comment by Laul0** [comment]
Hmm, I forgot to mention the informations about my environment sorry:

- Plateform: self-hosted (docker)
- Matomo version: 3.13.0

It is totally possible to organize a remote meeting I you wish of course, with pleasure.

**Comment by Laul0** [comment]
Not reproduce until the latest version
