### ISSUE TITLE
Enable Debugging mode without URL parameter

### ISSUE THREAD

**Issue by peterbo** [matomo-org/tag-manager#217]
The Debug mode doesn't seem to work without adding the mtmPreviewMode-Parameter to the URL. Enabling the Debug-Mode without the parameter would be nice, because often it is not possible to attach additional parameters (e.g. checkout funnel, security enhances sites with whitelisted parameter names, thank you pages, etc.)

**Comment by tsteur** [comment]
BTW @peterbo when enabling the preview mode, it currently sets a cookie so you don't need the URL parameters. The cookie should be valid for one week. However, it doesn't work when Matomo runs on a different domain which is often the case. 

We'd basically need to find a way to set a cookie on a different frame which maybe could be achieved if a landing page has the Matomo tracking code embedded. It would need to be quite save though ensuring this feature cannot be misused.

I suppose we'd need to have some URL parameter `websiteUrl?enablePreviewMode=$containerUrl` where the format of the container name would need to be checked strictly. This would then maybe set the cookie? If there are multiple urls configured we would need to try and set the cookie on all urls?

**Comment by peterbo** [comment]
Thanks for answering, Thomas! What mechanism did GTM base this on? Do they deploy a third party cookie? It seems like they deliver some kind of JSON debug configuration from the container-URL (which is the tracking server URL) if a debug & a session cookie is present and valid. But it seems to be pretty complex from what I can see. Probably an enhancement for later! Thank you!

**Comment by Laul0** [comment]
I opened an issue related to this one in the wrong repo: matomo-org/matomo/issues/15941

**Comment by Laul0** [comment]
In my case, if I enforce the domain into the cookie, the preview mode appears:

<img width="1367" alt="Screen Shot 2020-05-14 at 16 49 19" src="https://user-images.githubusercontent.com/15279205/81984879-76c65880-9603-11ea-9371-fb8fc4a8f5fc.png">

By default, the cookie domain is : `yourmatomo.domain.ext`

Edit this one with: `yourwebiste.domain.ext` and the preview appears.

> Note: the subdomains are different but the domain is the same in my case.

**Comment by utrautmann** [comment]
It's not only an issue with different domains. In my case is the preview cookie set to the same domain like my website, but no preview panel appears.

But the preview cookie contains a path "/piwik" , because Matomo is installed in mydomain/piwik/

![grafik](https://user-images.githubusercontent.com/25771066/97107447-e1f27b80-16c7-11eb-852d-45f78abe6b65.png)

As I edited the preview cookie path and changed the path to "/", then the preview panel appeared without URL parameter and the panel contained also, as I navigated through my website.

![grafik](https://user-images.githubusercontent.com/25771066/97107543-79f06500-16c8-11eb-8179-b8af88111f64.png)

**Comment by amenk** [comment]
Why not just set a cookie when the target-site is called with ?mtmPreviewMode= so at least the preview mode persits?

A workarkound is to check the cookie on the Matomo URL and then go to the tracket site's console to enter (replace ..... by the code)

    document.cookie = 'mtmPreviewMode=..........; expires=Sun, 1 Jan 2023 00:00:00 UTC; path=/'

**Comment by tsteur** [comment]
> Why not just set a cookie when the target-site is called with ?mtmPreviewMode= so at least the preview mode persists?

That was a workaround I was thinking if nothing else works 👍   The only thing might be that it's not super obvious how to disable it again unless you disable preview mode. But that be a similar issue when setting the cookie directly.

**Comment by csaeum** [comment]
> But that be a similar issue when setting the cookie directly.

Do you mean by setting cookies directly in the browser to set it by hand?

Is it currently possible to set a cookie by hand, etc.?
We just want to test the ordering process and would have to add the parameters by hand, which is not possible at the end of the process.

I have read that you can set such a cookie manually in the browser. But with what parameters?

**Comment by tsteur** [comment]
I think it should work when you execute below JavaScript in the browser developer tools. You only need to adjust the idSite and the tagmanager container ID. I didn't fully test it but I think it should work.

```
var idSite = '1';
var idContainer = 'abcdef';

document.cookie = 'mtmPreviewMode=mtmPreview'+idSite+'_' + idContainer + '%3D1';
```

**Comment by justinvelluppillai** [comment]
This was fixed in #355

**Comment by bshankarpandey** [comment]
The Matomo Tag Manager is not showing the debug or preview mode under websites page. I have placed the code in site (https://www.grunenthalhealth-campus.de/de-de 1)” but not able to see the Matomo tag manager’s preview mode under websites page.

**Comment by AltamashShaikh** [comment]
@bshankarpandey There is a JS error in your Matomo Configuration  can you resolve that first ?
The error us due to custom JS function

![Screenshot from 2022-05-16 11-44-10](https://user-images.githubusercontent.com/14902277/168530393-c128b2bf-c620-4b0b-8175-e254f983fa1f.png)
![Screenshot from 2022-05-16 11-44-00](https://user-images.githubusercontent.com/14902277/168530397-46ef9e34-1291-4219-bf26-6c7a6808256b.png)

**Comment by bshankarpandey** [comment]
> @bshankarpandey There is a JS error in your Matomo Configuration can you resolve that first ? The error us due to custom JS function
> 
> ![Screenshot from 2022-05-16 11-44-10](https://user-images.githubusercontent.com/14902277/168530393-c128b2bf-c620-4b0b-8175-e254f983fa1f.png) ![Screenshot from 2022-05-16 11-44-00](https://user-images.githubusercontent.com/14902277/168530397-46ef9e34-1291-4219-bf26-6c7a6808256b.png)

There is no such custom javascript in matomo

**Comment by AltamashShaikh** [comment]
@bshankarpandey Please check you variables created under Matomo Tag Manager which will have a custom JS function
Also make sure you are selecting the correct container ID when viewing Matomo variables

**Comment by bshankarpandey** [comment]
You are I could see custom variable there.
function() {
  var status = {{video_percent}} ;
  switch (status) {
    case 0;
      return 'Start';
    case 25:
      return '25%';
   case 50:
      return '50%';
case 75:
      return '75%';
case 100:
      return 'complete';
    
  }
}

**Comment by bshankarpandey** [comment]
S

> @bshankarpandey Please check you variables created under Matomo Tag Manager which will have a custom JS function Also make sure you are selecting the correct container ID when viewing Matomo variables

I have corrected and selected right containerId still facing issue. Not able to open debugger mode

**Comment by AltamashShaikh** [comment]
you need to fix the `var status = {{video_percent}} ;` you can hardcode it for now and later fix it, once done please publish the container again.

**Comment by bshankarpandey** [comment]
> @bshankarpandey There is a JS error in your Matomo Configuration can you resolve that first ? The error us due to custom JS function
> 
> ![Screenshot from 2022-05-16 11-44-10](https://user-images.githubusercontent.com/14902277/168530393-c128b2bf-c620-4b0b-8175-e254f983fa1f.png) ![Screenshot from 2022-05-16 11-44-00](https://user-images.githubusercontent.com/14902277/168530397-46ef9e34-1291-4219-bf26-6c7a6808256b.png)

Can you check now if any error is still there, bcoz still not working

**Comment by AltamashShaikh** [comment]
@bshankarpandey I can see the debug view
![Screenshot from 2022-05-16 13-29-56](https://user-images.githubusercontent.com/14902277/168546382-d71a0f47-7a5e-4e3d-9595-d94c38d20a36.png)

Please refer this [FAQ](https://matomo.org/faq/tag-manager/preview-debug-a-tag-manager-container/) to enable debug view

**Comment by bshankarpandey** [comment]
> @bshankarpandey I can see the debug view ![Screenshot from 2022-05-16 13-29-56](https://user-images.githubusercontent.com/14902277/168546382-d71a0f47-7a5e-4e3d-9595-d94c38d20a36.png)
> 
> Please refer this [FAQ](https://matomo.org/faq/tag-manager/preview-debug-a-tag-manager-container/) to enable debug view

Yes, thanks for your support 👍

**Comment by bshankarpandey** [comment]
How to call EVENT Tracking for (Category, Action, Label, Name, Value)  Using custom HTML  : _mtm.push method 
             var _mtm = _mtm || [];     and  _mtm.push({ });


simillar to below method which working but not supporting properly in matomo

_paq.push(['trackEvent', category, action, name, value, {dimension1: 'DimensionValue'}]);

**Comment by heurteph-ei** [comment]
@bshankarpandey , GitHub is dedicated to bug resolutions or feature requests... Not for support
Please ask at: https://forum.matomo.org/
