### ISSUE TITLE
Umlauts in Event (category|action|name), probably other fields, too, destroy variable strings in the same field

### ISSUE THREAD

**Issue by peterbo** [matomo-org/tag-manager#218]
This was reproduced on multiple instances:

![event](https://user-images.githubusercontent.com/1018973/73534040-6b6a6b00-4420-11ea-990b-ce2b990ec0a2.JPG)

This results in the following event to be logged:
![event-logged](https://user-images.githubusercontent.com/1018973/73534119-a8366200-4420-11ea-83bc-267f75a21867.JPG)

**Comment by tsteur** [comment]
Cheers @peterbo  created https://github.com/matomo-org/tag-manager/pull/219/files
