### ISSUE TITLE
Add options to choose where custom HTML is loaded

### ISSUE THREAD

**Issue by scysys** [matomo-org/tag-manager#22]
Like:

- Load HTML in the "BEGINNING" of the "< body />"
- Load HTML in the "END" of the "< body />"
- Load HTML in the "BEGINNING" of the "< head />"
- Load HTML in the "END" of the "< head />"

**Comment by tsteur** [comment]
I wonder... does it make much sense to differentiate between beginning head and end of head? Maybe should be always end of head when placed in the head so styles can be overwritten? On the other side we can just add it, in case it is useful to differentiate between the two heads
