### ISSUE TITLE
Explain what the Tag Manager "Enable DNT" setting in the Matomo Configuration variable does

### ISSUE THREAD

**Issue by Findus23** [matomo-org/tag-manager#225]
Inspired by a confusion in https://forum.matomo.org/t/browser-do-not-track-kills-active-opt-out-ability/36116

People get confused by the fact that they can enable DNT support both in Matomo and in Tag Manager. The tag manager setting should explain that it is just an addition client-side check that stops sending the data at all.

**Comment by cherkavi** [comment]
With/Without "Support Do Not Track preference" Tag manager JS part (client) doesn't send any data to server.

Tag Manager Debug/Preview is showing in the Logs that "firing this tag" but no requests in browser log.

**Comment by cherkavi** [comment]
Official docker container Matomo.
matomo              latest              4f05222e2406

Dry run working properly from browser: http://127.0.0.1:8080/matomo.php?idsite=4&rec=1
( it is nice to have the same for curl )

Error writing working properly:
```
docker exec -it apache_app_1 /bin/bash
sed --in-place  "s/define('PIWIK_PRINT_ERROR_BACKTRACE', true);/define('PIWIK_PRINT_ERROR_BACKTRACE', false);/g" /var/www/html/index.php
```

Debug flag is working as expected:
```bash
sed --in-place 's/debug = 1/debug = 0/g' /var/www/html/config/config.ini.php
```

UI ( JS ) code for sending "visits" and write down to table working properly
```sql
select * from matomo_log_visit
```

Tag manager ( Client part ) does not sending any requests to Matomo Server.
During the Debug/Preview sessions I see "fired events" but after "new version" and "publishing" and "switching off debug" - nothing
