### ISSUE TITLE
Tag names are not encoded

### ISSUE THREAD

**Issue by Chardonneaur** [matomo-org/tag-manager#230]
Hi there,
When I create a tag in Tag Manager with a ' within the title, the debug mode carries the name like &amp.
Could you please correct it?

**Comment by tsteur** [comment]
Cheers @Chardonneaur 

Can you maybe check if this patch works https://github.com/matomo-org/tag-manager/pull/231/files ?

You'd need to change that file, and then for example disable and enable the debug mode to regenerate the preview JS file
