### ISSUE TITLE
Matomo Tag Manager Workflow

### ISSUE THREAD

**Issue by liquidlx** [matomo-org/tag-manager#234]
Hello, I need to know if exists a workflow of how tag manager works, something visual. Thanks!

**Comment by tsteur** [comment]
Hi there, likely this month we'll publish a lot of videos around this.

**Comment by liquidlx** [comment]
Good to hear that! Keep me updated :) (if you already have a link for the youtube channel or something like that I appreciate)

**Comment by tsteur** [comment]
Check out https://www.youtube.com/playlist?list=PLu58d85wNIlYIogzrh7hJj5LUFcmN92M- and be great to let us know what you think
