### ISSUE TITLE
Add description/comment field to Tags/Triggers/Variables for better documentation of functionality

### ISSUE THREAD

**Issue by peterbo** [matomo-org/tag-manager#249]
This feature would come in handy when more than one person is administering the TagManager.

**Comment by tsteur** [comment]
Makes sense 👍

**Comment by Chardonneaur** [comment]
I confirmed that this need is still an existing one. I got today a measurement plan to implement, and within the spreadsheet documentation of the analyst, there is a line regarding the description of the variable. Definitely an optionnal line but still valuable.

**Comment by snake14** [comment]
@peterbo Thank you for taking the time to create this issue and suggest an enhancement. Tags, Triggers, and Variables should have description fields in Matomo version 4.12 forward.
