### ISSUE TITLE
TagManager _mtm dataLayer is an object not an array -> use Array for dataLayer

### ISSUE THREAD

**Issue by peterbo** [matomo-org/tag-manager#257]
In contrast to GA's dataLayer array, Matomo's _mtm datalayer is an object. Quite a lot of solutions, when it comes to consent management, plugins for CMS, shop integration plugins and so forth, implement a method to rename the datalayer variable name nowadays (to use another solution than GA). In most cases, this fails with _mtm, because it is not an array (it just implements some array methods).

I was wondering, what are the advantages/disadvantages of _mtm being an object vs being an array. Making _mtm an array could make Matomo's datalayer more compatible to a lot of tools out there.

**Comment by tsteur** [comment]
@peterbo I reckon it's an object because it's an object in the Matomo JS tracker too and was "copied" from there. We basically set 

```js
_mtm = {push: function () {
    ...
}};
```

so we get notified easily whenever someone pushed something to `_mtm`. I suppose there might be by now also some way to check if anything was pushed to `_mtm` , meaning the array was modified, with a plain array? Not sure how others do it. Basically as soon as someone pushes a value to this array, the tag manager code needs to be triggered to process this change.

**Comment by peterbo** [comment]
Jep, this makes sense!
Would it be possible to easily change that to a construction e.g.

```
_mtmArray = [];
_mtmArray.push = function (){
    return Array.prototype.push.apply(this,arguments);
}
```
So that it's an array with an overridden push function to notify the TagManager of a new element? I think that's basically how GA does it.

**Comment by tsteur** [comment]
I haven't tested it should be possible I reckon. If I see this right it might be fairly easy to do. 

> Quite a lot of solutions, when it comes to consent management, plugins for CMS, shop integration plugins and so forth, implement a method to rename the datalayer variable name nowadays (to use another solution than GA)

btw any chance you could explain a bit more what they do there and how it works with an array and not an object just to better understand what's happening?

**Comment by peterbo** [comment]
>btw any chance you could explain a bit more what they do there and how it works with an array and not an object just to better understand what's happening?

Definitely. There are probably more cases, but I have two examples at the moment:
1) One of the most popular consent solution tools here pushes its designated consented infos to the dataLayer:
![consents](https://user-images.githubusercontent.com/1018973/86970911-85973a80-c170-11ea-9b11-309c01e194f0.JPG)
For checking its own state and consents given, it expects array access to the dataLayer. (See forum: https://forum.matomo.org/t/matomo-hinter-usercentrics-consent-banner/36212/11). I'm in contact with the person in charge, but it doesn't seem easy to do. 
![consents-mtm-error](https://user-images.githubusercontent.com/1018973/86971391-6056fc00-c171-11ea-80e7-5671871b055d.JPG)

2) A lot of plugins for wordpress that support dataLayer integration expect an array structure. (e.g. Google Tag Manager for WordPress). In the plugin, you can also define another dataLayer variable name, but for e.g. the woocommerce integration, the plugin often checks the already pushed products (e.g. for product and recommended product listings) to not push a product more often than needed. 

In general from my experience, most plugins are designed to follow GA's dataLayer structure and are more and more introducing the capability to change the datalayer variable name. But changing the overall interaction (apart from the push function) logic is out of scope for most providers.

**Comment by tsteur** [comment]
@peterbo I haven't fully tested it but maybe something like this would work? https://github.com/matomo-org/tag-manager/pull/260/files
