### ISSUE TITLE
New "Click Button" variable and "All Elements Click" and "All Links Click" will trigger on middle and right click also

### ISSUE THREAD

**Issue by DanielBoch** [matomo-org/tag-manager#268]
I try to track for example a "Download Button" that opens another page instead of the current one. When I try to open it with firefox "open in new tab" than the MTM Debugger is not showing any click, windowload or download. This is true for all Buttons that open new pages.

I work with the Matomo Plugin for Wordpress.

![2020-08-31 14_56_40-Matomo Tag Manager Debugger](https://user-images.githubusercontent.com/49716644/91722560-b7d67e80-eb9a-11ea-9635-87a35dab286e.png)

**Comment by tsteur** [comment]
@DanielBoch thanks for creating this issue. Which click trigger are you using in the container? 

If you could additionally maybe also send us a URL to a page where we can reproduce this (including on what link to click) that might make it a lot easier for us to investigate. Feel free to send us the URL to wordpress at matomo.org

**Comment by DanielBoch** [comment]
The site I have this issue with is under construction right now and is not available to the public. But I can show you the version 1 of this site that is public (but not for very long as we are about to launch version 2): https://evolvingregions.com. You can try to get it to work with the download link section of the onepager.

I work with the normal "All Elements Click" impulse/trigger. I hope this helps.
Maybe with a video call or something I can show the issue on the current site.

**Comment by tsteur** [comment]
@DanielBoch I just checked out the site but it loos like the container is not embedded? Only the Matomo tracking code. Could you embed the container again?

**Comment by DanielBoch** [comment]
@tsteur Its supposed to work. Its behind a cookie consent: 
![MicrosoftTeams-image (8)](https://user-images.githubusercontent.com/49716644/91950168-9beced00-ed00-11ea-8581-0f8769f7e9a0.png)

**Comment by tsteur** [comment]
@DanielBoch I did give consent but the cookie consent tool js always triggering a JS error so I reckon this is why it's not loading 
![image](https://user-images.githubusercontent.com/273120/92042803-0bc9a900-edcf-11ea-9acb-9d2a5d7cc273.png)

**Comment by DanielBoch** [comment]
The thing is: This is the old version 1 of the page I am currently working on. I cant fix this issue because we are already working to launch the new site. It would make no sense to us to fix an issue on an already outdated site.
Maybe we should just wait for the launch of the new site so that you can see the issue I initially explained.

**Comment by tsteur** [comment]
sounds great @DanielBoch

**Comment by DanielBoch** [comment]
The final site is now online: https://evolvingregions.com/en/ Can you try and replicate the issue?
I encountered the issue I explained with several projects in the past so I kind of think its either a matomo issue or I am just to stupid. What makes me confident in trusting my abilities is that the same thing works with GTM but not with Matomo.

**Comment by tsteur** [comment]
Hi @DanielBoch just had a look but not getting any error. Not sure where I need to click to reproduce it?

**Comment by DanielBoch** [comment]
When you go to service: https://evolvingregions.com/en/services/ and click on request under "CONTACT PERSON". If you open it in  another tap the click is not showing in MTM Debugger. I cant explain it otherwise or I have to share my screen.

**Comment by tsteur** [comment]
Hi @DanielBoch I had another look. Preview mode is currently not enabled so I'm relying on information from so called "developer console logs". 

It seems a tag is triggered when clicking on it with a mouse click and I think one other tag is not triggered because of some block condition.

Do I understand it right you are basically meaning the tag is not fired when doing a `right click -> open in a new tab`? This I can reproduce. I haven't thought a lot about it but I guess this could be seen as expected behaviour to trigger this event also on a right click or middle click and we would then maybe need to add some additional variable information on which button was clicked.

**Comment by DanielBoch** [comment]
You are right. I mean the right click. You technically clicked it, it just opens in another window. So this action should count the same as a left click.

**Comment by tsteur** [comment]
Thanks @DanielBoch I've updated the title of this issue.

From what I understand in your previous comment is that GTM always triggers the click triggers on a middle or right click so it would make sense to behave the same for consistency.
