### ISSUE TITLE
TagManager gets deactivated periodically

### ISSUE THREAD

**Issue by b-r-u-h** [matomo-org/tag-manager#269]
Hi there,

since a couple of weeks we are facing issues with the TagManager. Although we defined the Plugin in the "config.ini.php" the plugin does not get activated if we deploy Matomo. Not only it does not get started but since a few weeks the TagManager plugin gets deactivated periodically and has to be activated again manually in System --> Plugins. Is there an option that we are missing that persists such plugin settings?

We have defined the TagManager like this in the "config.ini.php":

```
    [Plugins]
    Plugins[] = "TagManager"
 
    [PluginsInstalled]
    PluginsInstalled[]=TagManager
```

We use following image: [bitnami/matomo:3.14.0](https://github.com/bitnami/bitnami-docker-matomo) but it was already an issue in Version 3.13.4. This image is running on a Kubernetes cluster with k8s version 1.13.5. 

I already opened an issue on the bitnami project but i was told that this might be an issue with the TagManager directly rather then with the bitnami Image: https://github.com/bitnami/bitnami-docker-matomo/issues/61

Thanks in Advance!

**Comment by tsteur** [comment]
@b-r-u-h it only needs to be persisted in the config file and there's no other place. It seems the image is not reading the config file properly or has some other issues with it. I hate to say this but there might be an issue with the bitnami image (I checked in the code Matomo should not automatically disable that plugin). Sorry for referring you back to this but it doesn't sound like any issue here. I'm very happy to reopen though should for some reason this be an issue with Matomo though as well. Generally though the config file is the only place where it needs to be enabled.

**Comment by b-r-u-h** [comment]
@tsteur , Thanks for having a look at this. Will forward this to the Bitnami queue then
