### ISSUE TITLE
Tag Manager: Change the location of Preview window

### ISSUE THREAD

**Issue by KarthikRaja1388** [matomo-org/tag-manager#271]
Possibility of changing the location of Preview window.

**Request from a user:** We are working on measuring a chatbot. I use Matomo Tag Manager and the preview/debug functionality to test the triggers. However, because there is no option to minimize/resize the preview/debug mode i am not able to use this option on the chatbot. Since the chatbot is located at the right-bottom of the page (and the preview/debug mode overlays this).

**Comment by AltamashShaikh** [comment]
can anyone check #470 here?
will this solution be more useful or the solution discussed in comments to move to top will be more helpful?

**Comment by Starker3** [comment]
@AltamashShaikh #470 looks like a better solution to this problem. One thing I noticed though is that the preview window shows up at the bottom of the page and not at the bottom of the viewport when it first renders. This might confuse some people who are used to it showing at the bottom of the viewport always.
For example:
![image](https://user-images.githubusercontent.com/20905821/162114416-6bc0a693-9633-4e9f-8009-27d3350bf9a1.png)

Users would need to scroll to the bottom of the page to see it or to move it if the page is much longer (For example this might be a bigger issue on single page/infinite scroll websites)
![image](https://user-images.githubusercontent.com/20905821/162114547-756b5d74-d805-4422-aa72-c27b79cba293.png)

It might also be a minor issue for pages that are smaller than the viewport that it shows up in the middle of the page.

![image](https://user-images.githubusercontent.com/20905821/162114583-67a9ad88-3188-4d29-8588-0789c8902002.png)

Something that might also be useful for some people is if they could resize the preview mode window (But I guess its not really necessary for right now)

**Comment by AltamashShaikh** [comment]
@Starker3 I removed the previous solution of drag and drop and updated with a simple link "Stick to Top/Stick to Bottom"
