### ISSUE TITLE
Support for Multiple Matomo trackers

### ISSUE THREAD

**Issue by scysys** [matomo-org/tag-manager#286]
Based on: https://developer.matomo.org/guides/tracking-javascript-guide#multiple-piwik-trackers
It should be great to integrate the option for this directly inside the Matomo Configuration variable.

**Comment by tsteur** [comment]
Hi @scysys it should work to simply configure two Matomo Tags with two different Matomo configurations. Can you check if this is working for you?

**Comment by scysys** [comment]
@tsteur 

I didn't think of this solution. It´s working. Thanks!
