### ISSUE TITLE
Confusing English Label TagManager.FireDelayHelp 

### ISSUE THREAD

**Issue by baywet** [matomo-org/tag-manager#29]
Hi,
I came across a weird text in English, the wording is redundant and confusing.
I think it should be updated in English, the key is TagManager.FireDelayHelp and it reads:
"Lets you delay the execution of this tag once a fire trigger has been triggered. This can be useful if you want to wait for example for 3000ms (3 seconds) before executing the tag to allow for a blocking trigger to be triggered to avoid the tag from being triggered. The value is expected in milliseconds where 1000ms are equal to one second."
The part after the "(3 seconds) is particularly confusing.

**Comment by tsteur** [comment]
Can be definitely improved. What about something like

> Lets you delay the execution of this tag. This can be useful for example if you want to allow some time for a blocking trigger to stop the tag from being executed. The value is expected in milliseconds where 1000ms are equal to one second.

I can see though that it might still not be 100% there. We could also just remove the second sentence. Or add an example but right now cannot think of a simple to explain example real world example.

**Comment by baywet** [comment]
I personally think it's much clearer and avoids repetition compared to the previous version.

**Comment by baywet** [comment]
I saw the new label in transifex, closing
