### ISSUE TITLE
Preview does not work when # is in the URL

### ISSUE THREAD

**Issue by jmumby** [matomo-org/tag-manager#290]
If you have an URL like `https://example.com/#/login` and add the preview parameter `https://example.com/#/login?mtmPreviewMode=123xyz` the preview does not work. If you place the parameter before the # it does work fine e.g `https://example.com?mtmPreviewMode=123xyz/#/login` but the parameter is removed after the page loads.

**Comment by tsteur** [comment]
@jmumby not sure what you mean by "the parameter is removed after the page loads"? Do you have an actual URL where this can be reproduced?

**Comment by jmumby** [comment]
If you use the URL https://example.com?mtmPreviewMode=123xyz/#/login after the page is loaded the URL changes to https://example.com/#/login. If you are testing and want to reload the same page you would need to add the parameter each time. I will share a URL privately.

**Comment by tsteur** [comment]
@jmumby created https://github.com/matomo-org/tag-manager/pull/291 We will then look in the entire URL for the activation parameter. This should make this work so the URL parameter can be at the end. I can put this on cloud on next deploy already.

**Comment by tsteur** [comment]
Otherwise only https://github.com/matomo-org/tag-manager/issues/217 would help
