### ISSUE TITLE
No Error Messages When Calling Non-Existant Variable in Tag Manager

### ISSUE THREAD

**Issue by danieljwonder** [matomo-org/tag-manager#292]
I just spent a good while trying to discover why data from a certain tag wasn't being collected even though the tag was firing in the debug view. Ultimately it seems that the Matomo Configuration variable had been renamed but the Tag calling that configuration variable was still firing and looking for the old name. 

It seems to me that it would be good to either identify the tags via a unique persistent identifier to allow for renaming or throw an error message in the debugger when a tag is trying to call a non-existant variable, whether it is a Matomo configuration or otherwise.

**Comment by danieljwonder** [comment]
Ok, thanks. I'm not sure how it got out of sync but this was definitely the issue and it is working since I fixed it.

**Comment by AltamashShaikh** [comment]
Fixed with #524
