### ISSUE TITLE
When deploying Container, sometimes half of the logic is missing, tracking stops

### ISSUE THREAD

**Issue by peterbo** [matomo-org/tag-manager#315]
Even with minor or no changes to the TagManager / Container configuration, the deployment mechanism creates different containers with sometimes most of the business logic missing (Matomo 4.2.0). The example shows the same container, that is deployed just with a minor change. Interestingly, the change history of the Container always shows a bunch of Tags (even if they were not changed):

![container-differences](https://user-images.githubusercontent.com/1018973/113146489-054dc380-9230-11eb-907f-7f4b80f0ac0a.JPG)

**Comment by diosmosis** [comment]
Hi @peterbo, do you have steps to reproduce? Or it just that a deploy suddenly removes business logic?

**Comment by peterbo** [comment]
Hey @diosmosis! - It is really just publishing the release (Publish -> Create new version and publish release/without publish). Everytime this is done, the resulting container has other sizes and misses other parts.

**Comment by tsteur** [comment]
@peterbo can you reproduce this consistently? Is there anything special about this setup maybe?

**Comment by peterbo** [comment]
Hey @tsteur - nothing special with the setup really. Unfortunately, I don't have the setup under "control", so I'm also just checking the "surface". I already established, that there is a timeout while calling method=TagManager.createContainerVersion (Maximum execution time of 30 seconds exceeded).

But two things, I/we would have to figure out:
1) The release process, although timed out, created a container which is incomplete / doesn't incorporate all Templates / libraries - perhaps this could be made "transaction safe", so that only successfully finished / completed containers are published / released
2) Why it takes > 30 seconds on a strong server to process the container - I'll check the file system and other properties, why this takes so long.

**Comment by tsteur** [comment]
> Why it takes > 30 seconds on a strong server to process the container - I'll check the file system and other properties, why this takes so long.

Is it using the latest Matomo version? If not, I'd recommend upgrading and checking if this is still an issue. We added some detection for recursion like `variable a references variable b which references variable A` and would usually run in a loop

**Comment by peterbo** [comment]
Matomo 4.2.0 at the moment. Thank you both for the fast feedback! I'll report back after the update!

**Comment by AltamashShaikh** [comment]
@peterbo Is this still a issue or can we close this issue ?

**Comment by AltamashShaikh** [comment]
@peterbo Closing this issue, feel free to reopen if you are still facing the issue
