### ISSUE TITLE
Add option to deactivate a tag or trigger

### ISSUE THREAD

**Issue by peterbo** [matomo-org/tag-manager#319]
Sometimes, it would be very useful to deactivate / disable a tag / trigger, if you just need it from time to time (e.g. for A/B testing, or work in progress).

**Comment by tsteur** [comment]
Thanks for creating the issue @peterbo I'll close it as a duplicate of https://github.com/matomo-org/tag-manager/issues/23 where there's also a workaround mentioned (not ideal but works this way)
