### ISSUE TITLE
Restoring version, somewhat confused, it this a bug or just how it works?

### ISSUE THREAD

**Issue by Japhys** [matomo-org/tag-manager#324]
I am somewhat confused

Let's say I create Tag A and publish it
The create Tag B but delete Tag A and publish it
Restore version with Tag A

I go to Container -> Tags and I expect to see Tag A
Instead I see Tag B
It's not being fired though

Is this how it is supposed to work? Why does it not restore the complete container in the UI? 

So how do I take an older version as a new starting point then?

I am on 4.3.0b

**Comment by diosmosis** [comment]
Hi @Japhys, when you say "restore version with Tag A" do you mean re-publish the older version with Tag A (ie, the rocket button in the versions table):

![image](https://user-images.githubusercontent.com/125140/118710164-c7eac880-b7d2-11eb-8c3c-f2156319bce9.png)

?

**Comment by Japhys** [comment]
Hi @diosmosis yup that's indeed what I was doing.

**Comment by diosmosis** [comment]
@Japhys I see, I believe that just makes the previous version the live version, it doesn't restore the entities in Matomo to their previous state. Tag A will still be deleted in the Matomo UI, but it should still be available in the previous container version's JavaScript. Does that answer your question? And is it still inconvenient for you to not have access to the old Tag?

**Comment by Japhys** [comment]
I was wondering if this is how it works. Well I guess it will not be an issue I will run into often. But it would make sense to me to have access to all the tags triggers and variables from that re-published container. But maybe that's just me. But thanks for clearing it up!

The reason I ran into this was that I underestimated the strain Tag Manager can put on a server. I created a couple of tags which are being triggered in every visit and published them. But we have maybe 200.000 visits a day, so the UI was getting inaccessible all of q sudden. I went to revisions to republish the previous version and undo my latest tags. To my surprise the tags were not fired anymore but still in the UI, hence my confusion. If I decide not to use them anymore, I will have to delete them / clean up the UI and publish a new version. If I don't they will be published again next time, causing problems again. Easy mistake to make.

**Comment by tsteur** [comment]
@Japhys you might be able to achieve this by exporting a specific version and then importing it. You can export any specific version and then in the bottom there is an import button. The publish feature itself is supposed to not update the current "draft" version you are editing.

![image](https://user-images.githubusercontent.com/273120/118723248-4736d580-b881-11eb-91e9-ffe6942bec39.png)

**Comment by Japhys** [comment]
@tsteur Good one! I was actually wondering the same thing last night, I was pretty sure I did that before when migrating to a new installation a couple years ago, after that UI was up to date! 

Thanks

**Comment by tsteur** [comment]
Great @Japhys . Glad this worked. I'll close this issue for now

**Comment by heurteph-ei** [comment]
Hi @tsteur , maybe it could be good to disable the feature of publishing an old version if it does not work as could be expected... ?

**Comment by tsteur** [comment]
@heurteph-ei the feature works exactly as it is expected currently. It's not supposed to change the version you are editing, it will only update the environment you are publishing it to.
