### ISSUE TITLE
Fix for Tagmanager working along with CSP when triggering a HTML tag

### ISSUE THREAD

**Issue by KarthikRaja1388** [matomo-org/tag-manager#326]
Customer's explanation of the issue:

I create a nonce for the actual embed Script, read: the regular matomo one, and the embed script for the tag manager. These two codes work perfectly fine. No csp issues arrise here.
Now lets say, i create a tag, that for the sake of simplicity, fires on every click to the page. The tag it self is a "CUSTOM HTML" tag, that simply says: '<script>console.log("Hello from the Tag")</script>' and gets appended to the end of the html body.

When i now click on the webpage the tag gets fired and i get a csp viloation. "[Report Only] Refused to execute inline script because it violates the following Content Security Policy directive ...". From my understanding this is correct, as a script gets inserted that neither has a nonce nor a hash and therefore can not be deemed to be trustworthy. The tag-manager tho, gets loaded via a nonce and therefore is trustworthy, i'd now need a mechanism to add the nonce from the tagmanager to script elements that get created by the matomo tag manager too. And this is what i struggle to do. Adding it as a custom-var does not work (read from a header eg) as the tagmanagment script removes most attributes of scripts added.

Sure, I could use script hashes, but then i'd need to know every script i'll add beforehand and add its hash to my CSP-Header, which defeats the purpose of the tag management.

**Comment by snake14** [comment]
@KarthikRaja1388 Thank you for taking the time to create this issue. When Matomo version 4.12 is released, the fix will be included. It will make it so that scripts that are part of customHtml variables will automatically include the nonce attribute set on the main script element on the page. So, if you enable the Matomo JavaScript using a nonce, it should share that nonce with inline scripts that it adds to the DOM.

**Comment by acsama** [comment]
> @KarthikRaja1388 Thank you for taking the time to create this issue. When Matomo version 4.12 is released, the fix will be included. It will make it so that scripts that are part of customHtml variables will automatically include the nonce attribute set on the main script element on the page. So, if you enable the Matomo JavaScript using a nonce, it should share that nonce with inline scripts that it adds to the DOM.

Hello @snake14  when is the 4.12 release scheduled?  This feature is going to ease some pains we've having with csp right now in our project.

**Comment by AltamashShaikh** [comment]
@acsama We do not have an exact ETA, but we just released [4.12-rc1](https://github.com/matomo-org/matomo/releases/tag/4.12.0-rc1) and hopefully if it doesn't have any regressions or issue reported by users, we will soon release `Matomo-4.12`

**Comment by MatomoForumNotifications** [comment]
This issue has been mentioned on **Matomo forums**. There might be relevant details there:

https://forum.matomo.org/t/script-in-custom-html-tag-does-not-support-nonce-attribut/47495/2
