### ISSUE TITLE
Observe DOM element changes even when a user doesn't scroll on the page

### ISSUE THREAD

**Issue by mattab** [matomo-org/tag-manager#328]
currently in the "Element visibility" trigger (and possibly others), the DOM is re-scanned (only?) when a "Scroll" is detected. But sometimes, a new Element might become visible, yet the user is not scrolling (for example when the user clicks on a button and a new DOM element appears). The Element visibility trigger wouldn't be triggered in this case (until the user scrolls). 

In terms of solutions, I have no idea really.... but some thoughts anyway:
maybe there could be some possible improvements (ie. detect element visibility on "Click" as well as "Scroll" and maybe other events also).

**Comment by heurteph-ei** [comment]
I think if you solve #B, you'll solve #A.
But could "Observe DOM change" feature detect for example a pseudo-element displayed by CSS on the :hover selector?

**Comment by ishantsolanki-vakt** [comment]
I am facing exactly the same issue.
I initially thought the `Element Visibility Trigger` would serve the purpose. But i was wrong. It only works (in my case) when i resize the window.
I would like to capture events like When a modal was opened or when showing an error message for an incorrect validation. In such cases there is no scroll events happening.

**Comment by tsteur** [comment]
fyi splitted this into two issues: https://github.com/matomo-org/tag-manager/issues/339 because this one is a lot easier to implement compared to #339 and can therefore be put in current sprint etc
