### ISSUE TITLE
Visibility trigger add feature to observe DOM changes etc.

### ISSUE THREAD

**Issue by tsteur** [matomo-org/tag-manager#339]
from https://github.com/matomo-org/tag-manager/issues/328

we got another report from a user, which reads:

> On our registration page, we have a few steps that we want to track (email, details, password, [optionally] verification). They are each assigned an unique element ID, which we use in the tag manager, but only the first step is seen as visible. If we resize the window the visibility of the current step is triggered, because we do a layout change. But just clicking through the steps do not trigger the visibility triggers, despite the ID of the step existing in the DOM and being visible. **Google Tag Manager's visibility triggers works just fine for these steps, where there is an option to enable "Observe DOM changes". An option seemingly missing in Matomo Tag Manager.**

Here is what the element visibility trigger looks like in GTM: 

![image](https://user-images.githubusercontent.com/466765/119725870-948bf600-bec4-11eb-9d1d-5d57375b92bb.png)

Maybe we could introduce a feature "Observe DOM changes" like in GTM?

**Comment by justinvelluppillai** [comment]
@AltamashShaikh is this issue fixed and can be closed now?
