### ISSUE TITLE
Add option to filter events in Preview mode

### ISSUE THREAD

**Issue by Starker3** [matomo-org/tag-manager#340]
## Context:
Currently when creating triggers (For example an `All Elements Click`) that has a filter, an event is logged in the Preview mode for every trigger regardless of if the trigger condition was met or not or if it fired a tag or not.

This can cause issues, especially when users create more than a few triggers. It's not unreasonable for users that are tracking even a single website or application with the Tag Manager to have 20 or more triggers for various things. If for example all 20 of them were `All Elements Click` those 20 triggers would create 20 events in the Preview Mode for every single click and forces the user to click through every single event to find the one that fired a tag.

This is definitely the expected behaviour in a lot of cases, especially when troubleshooting or testing new triggers in order to determine if the Trigger is being detected correctly by the tag manager regardless of if the filter was matched or not (To determine if the cause is due to a filter or other incorrectly configured setting)

This issue is further compounded when users use a single container to track multiple websites, with each website having triggers and tags that were created specifically for each website.

## Possible solution:
Something like a toggle or checkbox that users can use to hide events that didn't fire any tags (And potentially the other way around - a toggle to show only events that didn't trigger any tags may be useful in some cases)

**Comment by imightmax** [comment]
Current use case for our product requires me to have quite a few events. We are looking at approximately 50 in our tracking plan. All events have unique triggers, often they are a `All Elements Click`. While debugging this causes the preview mode to fill up very quickly. Just a couple of clicks and I am looking at +- 100 events logged in the preview mode. 

Now as mentioned in the OP this can definitely serve a good purpose if you are trying to single out issues on filtering conditions. However it also makes it hard to just simply check quickly whether my tag has fired appropiately. My most common case is that I use the preview to test the trigger and the respective tag that is connected. 

Filtering the preview mode to only display triggers that have met their condition would greatly help in that case.

**Comment by Mazino888** [comment]
Hi all. Since I am new in analytics I would like to kindly ask a question in regard to Matomo Tag Manager. I have set up some tags and triggers, which do not activate in the preview mode. It is ONLY in preview mode that I am able to see on the Visitors Log the events of my actions. However, I tried to check if I could see those events without the preview mode, but it does not work unless I place at the end of the URLs interested page the partial link of matomo (?mtm_preview_mode= container ID).  How can I activate the tags and triggers without using the preview mode link? Thank you for your answers.

**Comment by Starker3** [comment]
Hi @Mazino888 
It sounds like you've not yet published the changes you've made to the "Live" version of your Matomo Container.
When using the Preview mode, you will automatically see the "Draft" version of your container.

You can find more information on publishing a container and all the changes you've made in our documentation: https://matomo.org/docs/tag-manager/#publish

**Comment by tsteur** [comment]
@Starker3 do you have a page public where this can be reproduced maybe? 

Maybe if the condition wasn't met, or can send us a zip with HTML + JS to reproduce it?

Generally, what we can potentially do, if a condition wasn't met, and we are about to post a duplicate event just like the previous event, then we could potentially skip it. 

This might not always work but potentially could be a compromise for both maybe but would need to be double checked.

Maybe we wouldn't want such a toggle or checkbox if we can avoid it so it works well by default. And it avoids needing to store the setting for this in a cookie etc.

We will need an example though to reproduce this and then see what works best.

**Comment by Starker3** [comment]
@tsteur I can see if I can get an example that's public.

I was thinking again about this - maybe a better option instead of trying to filter out events that did/didn't trigger anything would be to add a search/filter function to the preview mode? Since in most cases people are looking for a specific trigger or tag that fired we could maybe have a search box style filter to help them find the tag/trigger they're looking for in the preview mode.

**Comment by tsteur** [comment]
There's definitely value in showing events where conditions weren't met. We'll see what we do there. Maybe we signal met conditions a bit better or have a additionally a checkbox or some other ideas.
