### ISSUE TITLE
Element visibility trigger may trigger too often

### ISSUE THREAD

**Issue by tsteur** [matomo-org/tag-manager#362]
While testing #339 noticed a problem with the element visibility trigger.

I think this may have been an issue before, haven't checked though.

I have this configuration 
![image](https://user-images.githubusercontent.com/273120/132598293-053f1ce7-996d-46b0-8303-a7f014e0ae9e.png)

Where something should be triggered every time the element appears. It seems the scroll listener is triggering heaps of triggers. Sometimes twice per scroll etc. Even though it didn't disappear in between etc.

That's because on every scroll the element is still visible. Maybe we can change the logic eventually similar to the mutation observer where we check if the element is visible right now. If so, trigger the event. Then add an intersectionObserver for this element and not do anything again for this element in the "onScroll" event. thinking something like this maybe (not tested):

```diff
diff --git a/Template/Trigger/ElementVisibilityTrigger.web.js b/Template/Trigger/ElementVisibilityTrigger.web.js
index 3d307d6..0908d33 100644
--- a/Template/Trigger/ElementVisibilityTrigger.web.js
+++ b/Template/Trigger/ElementVisibilityTrigger.web.js
@@ -205,11 +205,15 @@
                             continue;
                         }
                     }
-                    if (nodes[i] && isVisible(nodes[i])) {
+                    if (nodes[i] && isVisible(nodes[i]) && !isDynamicNodeObservedForIntersection(nodes[i])) {
                         var percentVisible = getPercentVisible(nodes[i]);
                         if (!minPercentVisible || minPercentVisible <= percentVisible) {
                             commonTrigger(triggerEvent, percentVisible, nodes[i]);
                             commonTriggeredNodeCheck(nodes[i]);
+                        } else if (observerIntersection) {
+                                observerIntersection.observe(node);
+                                dynamicObservedNodesForIntersection.push(node);
+                            }
                         }
                     }
                 }
@@ -395,4 +399,4 @@
             TagManager.dom.onLoad(setIntersectionObserver(triggerEvent));
         };
     };
-})();
\ No newline at end of file
+})();
```

My page HTML was

```html
<p style="width:100%;height: 300px;background: red;" id="element2">test <a href="test.html">link</a> <a href="download.pdf">pdf</a></p><!-- Matomo Tag Manager -->
<div style="width:100%;height: 300px"> ererr</div>
<div style="width:100%;height: 300px"> ererr</div>
<div style="width:100%;height: 300px"> ererr</div>
<div style="width:100%;height: 300px" id="mytest"> test</div>
<div style="width:100%;height: 500px" id="element"> visible</div>
```
and while scrolling it would trigger the event quite often.

**Comment by AltamashShaikh** [comment]
I tested this on my local with following cases.
Observer only via Scroll - too often being triggered
Observer only via InterSectionObserver  - not triggered too often
Observer via Scroll + InterSectionObserver - too often being triggered
Observer via Scroll + InterSectionObserver + new condition - not triggered too often

Fixed in: https://github.com/matomo-org/tag-manager/pull/363
