### ISSUE TITLE
Richt clicks trigger twice for "All Links Click" and "All Elements Click" in Firefox

### ISSUE THREAD

**Issue by Starker3** [matomo-org/tag-manager#375]
It seems that Right Clicks trigger twice in Firefox for both All Links Clicks as well as All Elements Clicks

This can be reproduced with the following:
Setup an All Links Click or All Elements Click trigger (It's easier without any filters)
![image](https://user-images.githubusercontent.com/20905821/140679649-f084530b-435a-43df-a74c-34d4d6da2c92.png)

Setup a tag to send an event to Matomo
![image](https://user-images.githubusercontent.com/20905821/140679678-844ba432-8523-4210-aaf5-1ea31b502814.png)

Open the page in a browser tab and right click any link on the page - to be 100% sure, don't click anything else in the page at all during the visit.

Check the Matomo Visits Log:
![image](https://user-images.githubusercontent.com/20905821/140679814-ee2d1ca1-81aa-433b-aced-03a9db25030b.png)

The exact same steps performed in Chromium do not have the same issue:
![image](https://user-images.githubusercontent.com/20905821/140679882-d950e99b-3bee-453b-bd41-9e783d6866d8.png)

In the example above I have a pageview tag that sends a test event each time a page loads (Pageview trigger). The other two events are All Links Click and All Elements Click triggers.

Current Matomo version: 4.6.0-b2

This was originally reported from a Matomo Cloud user.

**Comment by mattab** [comment]
@Starker3 Thanks for creating the report. Could you confirm you have reproduced the issue and confirmed it?

**Comment by Starker3** [comment]
@mattab yes, I reproduced it in my testing instance. The screenshots were from that instance (self-hosted)

**Comment by AltamashShaikh** [comment]
@tsteur I was able to reproduce the same and the easiest fix is to check `e.which` and post that initiate a callback.
Currently: Event listener for `contextmenu` was triggering both middle and right click

**Comment by AltamashShaikh** [comment]
@Starker3 There is also a quick fix if we want to just track right clicks, we have a filter option called "Click button"
Refer: https://matomo.org/faq/tag-manager/how-do-i-get-the-click-triggers-to-only-trigger-on-left-middle-or-right-click/

**Comment by AltamashShaikh** [comment]
@Starker3 
Added a fix for this, but we need to wait till new Matomo version is released as this plugin is shipped with core.
