### ISSUE TITLE
FB pixel changed data type to string from INT

### ISSUE THREAD

**Issue by matmicro** [matomo-org/tag-manager#390]
Not able to save a Facebook Pixel ID in Matomo Tag Manager 4.6.1
It is always reset to value 2147483647.
This value correspond to the max possible value of INT.

Looking to the code looks that it could be solved by modifying :
Line 22 on  `plugins/TagManager/Template/Tag/FacebookPixelTag.php`

Replace :
`$this->makeSetting('pixelId', '', FieldConfig::TYPE_INT, function (FieldConfig $field) {`

By
`$this->makeSetting('pixelId', '', FieldConfig::TYPE_STRING, function (FieldConfig $field) {`

**Comment by AltamashShaikh** [comment]
@matmicro 
Thank you for reporting this, we have fixed this issue it will be released along with Matomo 4.7.
