### ISSUE TITLE
Top menu no longer visible

### ISSUE THREAD

**Issue by sgiehl** [matomo-org/tag-manager#393]
The top controls menu seems no longer to be visible with latest 4.x-dev version.
I guess this is related to the vue migration that is currently taking place.
The tag manager adds a custom control field to the menu. Maybe that doesn't work anymore.
Not sure if that needs to be fixed here on in core...

**Comment by AltamashShaikh** [comment]
@sgiehl 
Just FYI, this works in 4.6.1.
I did raise this with Thomas and he told it should be fixed once we merge the 4.6.1 branch back to 4.x-dev

**Comment by sgiehl** [comment]
Yes. That works with 4.6.1. This one is caused by the vue migration taking place in core, which is done by @diosmosis. Therefor I had already assigned the issue to her, to ensure it will be fixed before the next release. There is already a PR to fix this....
