### ISSUE TITLE
"En-/Disabling/ Share the preview" panel: Links are not working

### ISSUE THREAD

**Issue by utrautmann** [matomo-org/tag-manager#411]
Since Matomo 4.6 is in Tag Manager a new lightblue panel after activating the debug mode.

Neither the button (1) nor the deactivation link (2) work. When I click that, nothing happens. There is also no JavaScript error.
One more request: The FAQ link (3) opens in the same tab, which is not optimal. Can you please change that, that would be great?

![grafik](https://user-images.githubusercontent.com/25771066/150573081-9c745b42-c1f1-4deb-bbae-15d0faf77635.png)

Matomo 4.6.2 (german)
Firefox 96.0.1

**Comment by AltamashShaikh** [comment]
@utrautmann This issue was fixed in #383 
You need to update your Matomo core to latest version or you can simply append this to your debug URL
`{YOUR_URL}?mtmPreviewMode=XVIK4E2R&mtmSetDebugFlag=1` 

For the FAQ link we will try to open in new tab instead of same.

**Comment by AltamashShaikh** [comment]
@utrautmann The fix will go live with next release(Matomo 4.7) you can update your Matomo instance and reopen this issue if the issue still persists in Matomo 4.7 too.
