### ISSUE TITLE
Change color of button: Create new version (without publishing)

### ISSUE THREAD

**Issue by jorgeuos** [matomo-org/tag-manager#415]
Hi,

I just discovered that a client hasn't received data for a site for quite some time. It was because the tracking URL had changed, so they updated their Matomo Configuration Variable, but then pressed the "Create new version (without publishing)" instead of "Create new version and publish release". They both look the same and have the same color.

<img width="608" alt="Screenshot_2022-01-28_at_15_21_53" src="https://user-images.githubusercontent.com/21176316/151563463-b84756e3-26b1-45e2-a6d7-dd8b5c34d8fe.png">

Very unfortunate.

I could go into UX think and refer to design principles and quote Donald Norman, but I think you understand the disambiguity of having the same color on two buttons in the same view that does two different things.

I suggest an orange color, even if you're color blind, you would probably notice a different shade.

Perhaps a confirm dialog would make it bulletproof.

`#designforerrors`

**Comment by tsteur** [comment]
Makes sense @jorgeuos thanks for the suggestion. I put it in the current milestone.

**Comment by AltamashShaikh** [comment]
Hey @jorgeuos thanks for the feedback, we have implemented the change suggested and should be available with Matomo 4.8.
