### ISSUE TITLE
Trim whitespace from matomoUrl,idSite,cookieDomain and cookiePath fields

### ISSUE THREAD

**Issue by peterbo** [matomo-org/tag-manager#421]
Whitespaces are not trimmed from (text) input fields. That often results in errors, when copy/pasting information from other sources.

![trim_input_fields](https://user-images.githubusercontent.com/1018973/153584832-ac4752ab-ee35-4273-9112-ef608dbc478c.PNG)

**Comment by sgiehl** [comment]
I guess we shouldn't do that automatically for all input fields, as a leading or trailing whitespace might in some cases be added on purpose. But for some fields I guess it makes sense to prevent such problems...

**Comment by peterbo** [comment]
@sgiehl - Definitely a good point! However, for most input fields, the need for trailing / leading whitespaces are the rare exception and trimmed inputs are the "default". But e.g. for "chained" inputs (or things that get concatenated somewhere), this absolutely makes sense to have untrimmed inputs.

**Comment by tsteur** [comment]
We could do this for few specific parameters fairly quickly. Like above the URL and idSite, cookieDomain, etc. Also for some other variables. If we're in doubt if it should be done, then we wouldn't.

**Comment by heurteph-ei** [comment]
... Or else just trim in case of (copy)-paste... ?

**Comment by AltamashShaikh** [comment]
> ... Or else just trim in case of (copy)-paste... ?

@heurteph-ei we are trimming after you have saved, so it wont matter if its copy paste or by typing

**Comment by heurteph-ei** [comment]
> ... Or else just trim in case of (copy)-paste... ?

Was just to apply the same rule on all fields without having to check for each field if white spaces are welcomed or not (for sure you will forget some, and maybe also trim one that should not)...
If the user specifically type a white space, the user interface won't escape it without let him know.
