### ISSUE TITLE
403 error when trying to post custom JavaScript Variable

### ISSUE THREAD

**Issue by Jaimeapo** [matomo-org/tag-manager#433]
I'm using Matomo 4.7.1
and when I'm trying to create a new Custom JavaScript Variable it doesn´t save any changes
seems to be a rights problem but I've been able to create other kind of variables without problem.
![image](https://user-images.githubusercontent.com/2892389/154479289-6ace6e18-aa1b-4abe-a95c-1351411167a2.png)

**Comment by tsteur** [comment]
@Jaimeapo this looks to me like your webserver is maybe blocking this request. Could you ask your sysadmins if there is maybe a web application firewall active that could block such a request?

**Comment by Jaimeapo** [comment]
Thanks @tsteur , for quick answer, but why can I create other variables that doesn't use JavaScript?  are "Custom JavaScript" variables using other port to be saved?

**Comment by Jaimeapo** [comment]
Yes it was behind a firewall

**Comment by tsteur** [comment]
@Jaimeapo the firewall probably doesn't like certain words or characters in the request like `function(`
