### ISSUE TITLE
Change maximum allowed value for Facebook Pixel ID

### ISSUE THREAD

**Issue by atom-box** [matomo-org/tag-manager#434]
User writes:
_"
I am currently facing a bug with Matomo 4.6.1
When using Matomo Tag Manager in order to use Facebook Pixel ID.

I can't save my ID, which is greater than the maximum value of an INT.
then the value saved is always reset to 2147483647

Could you please provide a fix asap ?

Trying to save this field :"
![bug1](https://user-images.githubusercontent.com/22874146/154577283-7ef10bc2-6d45-41a3-8e87-973ccbb62497.png)
![bug2](https://user-images.githubusercontent.com/22874146/154577311-41100435-7f68-4210-b237-5c7b78aeaf8d.png)
_

**Comment by tsteur** [comment]
fyi @AltamashShaikh this might be a quick fix

**Comment by matmicro** [comment]
It has been fix3d in 4.7
Duplicate of https://github.com/matomo-org/tag-manager/issues/390

**Comment by tsteur** [comment]
Great, thanks for this @matmicro
