### ISSUE TITLE
Variable type shows variable name instead of type

### ISSUE THREAD

**Issue by ben-dw** [matomo-org/tag-manager#444]
Seems to be a small bug, that the variable **type** is now the same like the variable **name**.
![Bildschirmfoto 2022-03-10 um 17 48 11](https://user-images.githubusercontent.com/43407231/157713366-07c002c3-1eeb-476e-bd33-e33203f4bc20.png)

Matomo Version 4.8

**Comment by sgiehl** [comment]
@diosmosis might that be a Vue regression?
