### ISSUE TITLE
Changes to Custom Title or Custom URL on existing Pageview Tag doesn't allow saving the changes

### ISSUE THREAD

**Issue by Starker3** [matomo-org/tag-manager#446]
With the recent update to 4.8.0 it seems that making changes to a "Pageview" tag's Custom Title or Custom URL options is not detected as a change that would allow you to save the tag. For example a tag before making any changes:
![image](https://user-images.githubusercontent.com/20905821/157759133-dc53b558-3026-41a9-b5b6-901d95e5a69e.png)

And after making changes to both the Custom Title and the Custom URL it doesn't allow the changes to be saved (A change of either on its own also has the same issue):
![image](https://user-images.githubusercontent.com/20905821/157759220-ff75bab3-579c-456a-9222-0f102fac0af0.png)

The only way to have the changes detected and allow you to save is to either change the Tag's name or add/remove a trigger (For example adding and removing a `space` character to the name works to allow it to be changed

**Comment by sgiehl** [comment]
@diosmosis might be vue related as well.
