### ISSUE TITLE
Fix bug preventing "0" value for trigger condition

### ISSUE THREAD

**Issue by ben-dw** [matomo-org/tag-manager#450]
Good morning,
I'd like to use "0" or "1" as conditions but I get an error no matter which type I choose (equals, equals exactly, regex):
![Bildschirmfoto 2022-03-11 um 09 00 23](https://user-images.githubusercontent.com/43407231/157826746-372e6bc1-7898-443c-9fa7-9505d14b5d85.png)

**Comment by sgiehl** [comment]
Hi @ben-dw. Thanks for reporting this issue. I'll prepare a PR to fix that.
