### ISSUE TITLE
Selecting Start/End Date in Tag doesn't allow for changes to be saved

### ISSUE THREAD

**Issue by Starker3** [matomo-org/tag-manager#456]
There are actually two different issues here:

1. When you select a Start and/or End date for a tag using the UI  dropdown, it doesn't allow you to save the changes. If you edit any other options in the tag such as name, fire delay, priority, etc. it does allow you to save the changes. But in that case, only the Time is saved without the actual date.
2. When you do have the option to save the changes for example by changing something else in the tag, it only saves the time:
![image](https://user-images.githubusercontent.com/20905821/158081003-7f0fb6a8-de36-4d27-87f3-78e34ed9953a.png)

Manually entering the date or changing the date after using the UI to select it allows the changes to be saved and persisted:
![image](https://user-images.githubusercontent.com/20905821/158081039-8b878836-06b7-442d-87e3-a48f40e3f0df.png)

But you need to do this for both dates.

I tested using the changes from both these commits: https://github.com/matomo-org/tag-manager/pull/447
https://github.com/matomo-org/tag-manager/pull/445 
So it looks like a different issue to me.

**Comment by AltamashShaikh** [comment]
@diosmosis is this related to vue changes ?

**Comment by diosmosis** [comment]
Yes, looking into this now.
