### ISSUE TITLE
Tag Priority (and possibly other settings) not being saved anymore

### ISSUE THREAD

**Issue by peterbo** [matomo-org/tag-manager#459]
The last update -> Matomo 4.8.0 introduced a regression:

Reproduce with the following:
- Open Tag Configuration
- change Tag Priority (e.g. from 999 to 950)
- save the setting
- Reload the Tag configuration - The Tag priority is still 999

**Comment by tsteur** [comment]
@diosmosis @justinvelluppillai is this maybe a regression similar to https://github.com/matomo-org/tag-manager/issues/456 ?

**Comment by diosmosis** [comment]
Created a fix in #460
