### ISSUE TITLE
Set disableBrowserFeatureDetection with Tag Manager

### ISSUE THREAD

**Issue by chopsol** [matomo-org/tag-manager#471]
We need an option to set disableBrowserFeatureDetection introduced in 4.8.0 with Tag Manager. (https://matomo.org/faq/how-to/how-do-i-disable-browser-feature-detection-completely/)
I tried different ways via custom HTML, but it wasn't successful. Sometimes it works, sometimes it don't work, so there will be two different client_ids for one visitor having some pageview here and some actions there.

If someone has a working setup, please answer here also: https://forum.matomo.org/t/mtm-and-disablebrowserfeaturedetection/45405

**Comment by AltamashShaikh** [comment]
@chopsol This is already implemented in #449  and would go live with Matomo 4.9
