### ISSUE TITLE
400 Bad request after adding tag manager

### ISSUE THREAD

**Issue by santoshyadavdev** [matomo-org/tag-manager#476]
We are getting 400 bad request after adding tag manager, I can see the below error in console.

https://matomo.xxx.com/matomo.php?action_name=action_name&idsite=&rec=1&r=705306&h=12&m=18&s=3&url=https%3A%2F%2Fxxx.com%2Fapp%2Fsearch%3FmtmPreviewMode%3D82VmGOa2&_id=4c6fa0f44972ac20&_idn=1&_refts=1651659484&_ref=%2Fapp%2Fsearch&send_image=0&pdf=1&qt=0&realp=0&wma=0&fla=0&java=0&ag=0&cookie=1&res=1728x1117&pf_net=68&pf_srv=32&pf_tfr=0&pf_dm1=11&pf_dm2=4784&pf_onl=1&pv_id=asZYWH

After this failed request I can see success request too, when I tried to debug the exception is thrown by `dB = g.sendBeacon(du, dt)` this first request send idsite=emptyValue, I thought is what is causing this issue.

But in preview mode in log I can see everything is right
<img width="1142" alt="Screenshot 2022-05-04 at 12 28 56" src="https://user-images.githubusercontent.com/11923975/166665034-59f93d7f-3db8-4f97-a3fb-20be83ebe78a.png">

**Comment by AltamashShaikh** [comment]
@santoshyadavdev can you check if you are setting the `Matomo idSite` field correctly ?
Also how do you define your idsite in Matomo Configuration variable via some another variable or is it hardcoded ?

**Comment by santoshyadavdev** [comment]
We are using single container approach, where we have configured multiple siteid and injecting the container code directly in the app, using this approach we don't need to pass the siteid, and this happens on only first call, post this I can see success call and even everything is tracked properly with the correct instance and tags configured work.

**Comment by AltamashShaikh** [comment]
@santoshyadavdev Is there any URL/site on which we can check this behaviour ?

**Comment by santoshyadavdev** [comment]
Hi @AltamashShaikh,

Unfortunately this is an internal site and not available publicly, once it it available I can share.

**Comment by santoshyadavdev** [comment]
closing this as we figured it out.
