### ISSUE TITLE
Sometimes, Variables do not get resolved in the container - {{Variable name}} is parsed directly

### ISSUE THREAD

**Issue by peterbo** [matomo-org/tag-manager#483]
In some containers, even after re-publishing a containers, Variables do not get resolved and the (old) placeholder name {{Variable}} is included in the container output.

In this case, the container was imported via JSON import and the Variable is a matomoConfig which is correctly referenced in the tags. Changing the matomoConfig variable name, changes also the referenced matomoConfig, that is selected in a tag. So in the TagManager, the reference is correct, but an old variable name is output into the container.

![tag-config](https://user-images.githubusercontent.com/1018973/168282405-1c8de550-57ef-4c54-90ff-bd65b6c1da2f.JPG)
![variable-name](https://user-images.githubusercontent.com/1018973/168282411-ee388118-027d-42a8-ad92-4b9851441f32.JPG)
![container-output](https://user-images.githubusercontent.com/1018973/168282413-c79c7948-760f-4ce3-aba1-7e598f12c27d.JPG)

**Comment by AltamashShaikh** [comment]
@peterbo Can you help with more detailed steps to reproduce this ?

**Comment by tsteur** [comment]
ping @peterbo

**Comment by peterbo** [comment]
Hey guys, sorry for not reporting back. I tested importing the container on a newer version (4.9.0) and the instance in question was also updated in the meantime. All variables / configuration variables have now been resolved correctly (export -> import). So whatever went wrong, it seems to be fixed already.
