### ISSUE TITLE
{⁣{UserAgent}} in Tag Manager is empty

### ISSUE THREAD

**Issue by jr-ewing** [matomo-org/tag-manager#488]
The Variable {⁣{UserAgent}} in Tag Manager is empty

## Expected Behavior
I want to integrate the pre defined User Agent as a custom Dimension.
I expected that i get values like "Mozilla/5.0 (X11; Linux x86_64; rv:100.0) Gecko/20100101 Firefox/100.0" 

## Current Behavior
I added {⁣{UserAgent}}{{RandomNumber}} in the custom dimension fields. The fields i using are in the matomo configuration variable - on the button. The random Number is written to the dimension - the user Agent is empty.

## Possible Solution
console.log(window.navigator.userAgent); 

is giving the right value

**Comment by AltamashShaikh** [comment]
@jr-ewing I tried replicatio your issue and I can see the data being logged correctly
![Screenshot from 2022-05-30 08-38-51](https://user-images.githubusercontent.com/14902277/170910169-0feaff39-f6e7-4c3e-81a3-6e9bd0b0df02.png)

Same is being displayed in reports
![Screenshot from 2022-05-30 08-39-42](https://user-images.githubusercontent.com/14902277/170910233-1bdc6c68-47d1-4639-bc73-970bfd22f159.png)

**Comment by AltamashShaikh** [comment]
@jr-ewing Which browser and Matomo version are you using ?

**Comment by jr-ewing** [comment]
Firefox 102.0.1 (64-bit) on Linux Mint
Matomo 4.10.1

Sorry - seem to be fixed ....
