### ISSUE TITLE
Also translate tag parameter descriptions

### ISSUE THREAD

**Issue by Findus23** [matomo-org/tag-manager#49]
https://github.com/matomo-org/tag-manager/blob/cb9826810977a550f547514ffdef414b6aabdba3/Template/Tag/CustomHtmlTag.php#L39

At the moment the descriptions of tag parameters are not translated. Ideally there should be a default translation key similar to the tag description.

**Comment by Findus23** [comment]
Interestingly there is 
https://github.com/matomo-org/tag-manager/blob/f5db47ffc05225ad25f4eeb92c22f503a731e107/lang/en.json#L133

which has another description (which is translated and shown in the UI), so maybe the only thing left to do is remove the unused hardcoded descriptions.

**Comment by AltamashShaikh** [comment]
Fixed in this PR : https://github.com/matomo-org/tag-manager/pull/358
