### ISSUE TITLE
Add Click Value as variable

### ISSUE THREAD

**Issue by Starker3** [matomo-org/tag-manager#490]
There currently isn't a way to get the value of a page element as a variable in the Tag Manager. For elements that don't have a text value this means that it's not possible to dynamically track the value of those elements in the Tag Manager.

This could be useful for things such as Checkboxes, Radio buttons, etc. that only have a value without any text set in the element directly and usually have a text element adjacent.
For example you would normally have:
```
<input type="radio" value="0-25"><span>0-25</span>
```
Since only the checkbox is expected to be clicked, it won't be possible normally to get the value as a variable.

**Comment by heurteph-ei** [comment]
Or better (more flexible): define the attribute in which reading the value to track.
Eg:
```
<div class="some-classes" my-own-attribute="I want to track it">...</div>
```

**Comment by atom-box** [comment]
This was requested today. A user writes:

> we would like to track the entries/results in a feedback form. What solutions does Matomo offer for this?

![image](https://github.com/matomo-org/tag-manager/assets/22874146/db4f48cd-8e7f-44aa-949a-ca0312bb66f2)

**Comment by AltamashShaikh** [comment]
@atom-box how are they planning to track this requests ? On a form submit or whenever each checkbox is ticked ?

**Comment by heurteph-ei** [comment]
@atom-box I had some customers with such needs. My solution was the use of one action custom dimension for each checkbox... (I activated the whole 60 custom dimension in Matomo server config...)

**Comment by snake14** [comment]
@Starker3 The new variable type should be available with the next Matomo release.
