### ISSUE TITLE
Show info icon documentation links when defining triggers

### ISSUE THREAD

**Issue by Chardonneaur** [matomo-org/tag-manager#495]
Hi there,
When defining a trigger, there is no information icon dealing with what the variables are about.
Though, when we look at the variable panel, there are those information icons.
Would it possible to make those information icons available as well when defining a trigger.
Typical use case: click button variable definition.

**Comment by snake14** [comment]
Hi @Chardonneaur Thank you for creating this issue. I think that I've made the change that you requested, but want to confirm. Does the following look like what you were hoping for?
![image](https://user-images.githubusercontent.com/11394099/182243489-9d720e75-2ea5-475e-bf49-5af1711c32cd.png)

**Comment by Chardonneaur** [comment]
@snake14 you are exceptionnal this is exactly what I wanted thank you

**Comment by snake14** [comment]
@Chardonneaur thank you. The changes should be released as part of Matomo version 4.12.
