### ISSUE TITLE
Translation TagManager.CustomHtmlTagHelp

### ISSUE THREAD

**Issue by ulcuber** [matomo-org/tag-manager#498]
Said about tag but then mentioned trigger:

    The Custom HTML tag allows you to embed any tag which is not supported yet. The possibilities with this **trigger** are pretty much unlimited.

**Comment by sgiehl** [comment]
Hi @ulcuber. 
Thanks for the report. I'm not deep enough into this one to confirm if the description is correct or not. But if it isn't correct, feel free to create a pull request to fix it.
The string can be found here: https://github.com/matomo-org/tag-manager/blob/4.x-dev/lang/en.json#L137

**Comment by ulcuber** [comment]
@sgiehl OK. I have started translating through weblate and come to this inaccuracy. I was not sure if it should be changed via source or through weblate: https://hosted.weblate.org/translate/matomo/plugin-tagmanager/en/?checksum=5445c10490cdd163&q=CustomHtmlTagHelp&sort_by=-priority%2Cposition
Since English is a main language I was not able to edit that on weblate

**Comment by sgiehl** [comment]
English needs to be changed in source.
