### ISSUE TITLE
Enhancement: Server-Side Tagging with MTM

### ISSUE THREAD

**Issue by atom-box** [matomo-org/tag-manager#509]
In July, one user asked if they could, 
_"use Matomo Tag Manager for the implementation of Tags in server side."_

In May, one user asked does Matomo have,
_"Server-Side Tag Manager (similar to GTM Server Side, but obviously, sticking with Matomo, and staying away from all ____ products; so anything else outside of ____ cloud too). This is for analytics, but not for tag management. Do you have anything for server side tag management please? "_

In March one user asked, 
_"This maybe a really stupid question, but does Matomo support Google GTM Server-side Tagging?"_

**Comment by atom-box** [comment]
In June a user asked:

"Most of the infrastructures I maintain are currently shifting towards server side tag management (to mitigate effects of GDPR, iOS script blocking). I am currently unaware of the Matomo efforts in this field."

**Comment by AltamashShaikh** [comment]
@atom-box I have added for prioritisation and the product team will take a call on this.

**Comment by mattab** [comment]
Thanks @atom-box for creatng this issue :muscle: 

I've copied your valuable comments into the other issue and marking this as duplicate https://github.com/matomo-org/tag-manager/issues/305
