### ISSUE TITLE
Be able to copy tags

### ISSUE THREAD

**Issue by NanorPiwik** [matomo-org/tag-manager#51]
GTM has this feature. It is basically just a link provided within the settings of a given tag.
When you click on it, it directly create a new tag with the same settings of the previous one and you can already edit the settings to have this new tag up and running.

**Comment by heurteph-ei** [comment]
Hi @snake14 @Stan-vw
As #615 and this #51 are duplicate, I think one of them should be closed...

**Comment by snake14** [comment]
Hi @heurteph-ei . Yeah. I thought about closing one, but I wasn't sure. I guess since we're moving the other issue forward in priority, we can close this one.
