### ISSUE TITLE
Improve Start and end date for Tags handling of timezone

### ISSUE THREAD

**Issue by Starker3** [matomo-org/tag-manager#511]
We had a user that was having issues when configuring a tag with a specific start date and end date.

While investigating this issue, I found that the Start and End time for a Tag that is stored in UTC will be treated as that time in any timezone and not be converted to that visitors timezone.

For example, if we create a Tag such as the following:
![Thursday-14-07-2022 11-24-15](https://user-images.githubusercontent.com/20905821/178853974-68cdc0d2-bdd2-492a-ab9c-173cc69c73b3.png)
In the above example the start date is set as 1 AM July 14 NZST with end date 8 PM July 14 NZST
When this is converted to UTC, the start date is 1 PM July 13 UTC with end date 8 AM July 14 UTC

When we then test this tag in the browser, the tag does not fire with the following in the logs:
![Thursday-14-07-2022 11-24-28](https://user-images.githubusercontent.com/20905821/178854157-8536fff5-9829-48e4-b537-439f8b845241.png)
`not firing as this tag does not match date` 
However, the time of my device when testing was 11:20 AM NZST or 11:20PM UTC

When I changed the End Date of the tag to one day further (8 PM July 15 NZST, 8 AM July 15 UTC), it fired correctly as it detected the End Date time had not occurred yet:

![Thursday-14-07-2022 11-26-01](https://user-images.githubusercontent.com/20905821/178854334-ae49f462-0fe1-4e94-9401-eb3cd18d0644.png)

This indicates that the time for the start/end date is converted to UTC but is used in the browser as the local timezone of the browser.

**Comment by AltamashShaikh** [comment]
@Starker3 I have checked earlier versions too before VUE migration and its not a regression, we convert and store in UTC and post that we check if the visitor current time is in between the converted start and end datetime

@tsteur Just confirming this is how it is supposed to be right ?

**Comment by Starker3** [comment]
@AltamashShaikh 
I think this behavior has been the same since it was implemented. But the way it works currently would basically mean the tag would fire for some visitors some of the time.

**Comment by AltamashShaikh** [comment]
@Starker3 Yes, its the same may be we should convert the visitors local time to UTC to do the comparison and it will be consistent for everyone, as currently the tag will fire/not fire depending upon visitors timezone and it will give a wrong impression on data.

**Comment by Starker3** [comment]
@AltamashShaikh Do we know yet if this issue is going to be worked on?

**Comment by justinvelluppillai** [comment]
@Starker3 We haven't yet prioritised it to be done. If you have other users waiting for this it would be good to let us know in this issue also

**Comment by Starker3** [comment]
@justinvelluppillai We currently just have the one user that reported this issue waiting on a fix.
But with what the issue is, it likely impacts every user that makes use of this feature in the tag manager. But with how it is currently, they might not realise it until they look more closely at the data and investigate why some actions are tracked before & after the dates & times set in the tag manager.

**Comment by AltamashShaikh** [comment]
@Starker3 Should be fixed with release of Matomo 4.12, we will convert the user datetime to UTC during visit and check if its in the specified period defined and fire accordingly.

**Comment by Starker3** [comment]
Thanks @AltamashShaikh !
