### ISSUE TITLE
Preview modus not opening 

### ISSUE THREAD

**Issue by ChrisjuhNL** [matomo-org/tag-manager#513]
Preview mode is not opening on our website (https://www.avg-programma.nl/?mtmPreviewMode=5C94FOGl)

The following error message is displayed:
"Uncaught TypeError: Cannot read properties of null (reading 'addEventListener')  at (index):942:58"

But this is referring to non matomo code.
<img width="1039" alt="Schermafbeelding 2022-07-19 om 11 59 03" src="https://user-images.githubusercontent.com/8157056/179723910-79f53dac-a643-4040-9215-0064fa774e34.png">

**Comment by AltamashShaikh** [comment]
@ChrisjuhNL 
https://www.avg-programma.nl/?mtmPreviewMode=5C94FOGl&mtmSetDebugFlag=1 should be the url

**Comment by AltamashShaikh** [comment]
You should ideally load the url to debug via this input
![F1BCA00A-8972-4FB7-ADBD-EF68DCA91003](https://user-images.githubusercontent.com/14902277/179726273-cc1cd006-2b25-4c65-8f8d-aa3dc24bb970.jpeg)

**Comment by AltamashShaikh** [comment]
@ChrisjuhNL I will close this issue for now
