### ISSUE TITLE
Preview Tool not working when looking at more than first event

### ISSUE THREAD

**Issue by damzallagmythic** [matomo-org/tag-manager#517]
Hey Matomo team,

I've been looking to integrate more tags in the tag manager, but I am unable to click on other elements when in the debug mode.  Is this something that you all have seen and have a solution for?

I've attached a screenshare of how the debugger looks when going through this flow.  I'm also unable to go back to the original screen without refreshing the page which wipes all actions I've done on the page previously.

I also get this error in the dev console when this happens:
index.php?module=Proxy&action=getCoreJs&cb=5da3ae6757b8a06c31fa536f2687f506:41 TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'HTMLSpanElement'
    |     property '__reactFiber$408aa2b2iz5' -> object with constructor '$i'
    --- property 'stateNode' closes the circle
    at JSON.stringify (<anonymous>)
    at Proxy.xb (index.php?module=Proxy&action=getUmdJs&chunk=2&cb=5da3ae6757b8a06c31fa536f2687f506:269:14445)
    at Dt (index.php?module=Proxy&action=getCoreJs&cb=5da3ae6757b8a06c31fa536f2687f506:41:14750)
    at fe.fn (index.php?module=Proxy&action=getCoreJs&cb=5da3ae6757b8a06c31fa536f2687f506:41:40794)
    at fe.run (index.php?module=Proxy&action=getCoreJs&cb=5da3ae6757b8a06c31fa536f2687f506:41:5356)
    at Rr (index.php?module=Proxy&action=getCoreJs&cb=5da3ae6757b8a06c31fa536f2687f506:41:56630)
    at es (index.php?module=Proxy&action=getCoreJs&cb=5da3ae6757b8a06c31fa536f2687f506:41:58194)

[Matomo Blankos Clip 1.zip](https://github.com/matomo-org/tag-manager/files/9168422/Matomo.Blankos.Clip.1.zip)

Let me know if you need additional info on the container here or account and whatnot.  The webisite here is blankos.com (the dev version)

**Comment by AltamashShaikh** [comment]
@damzallagmythic Can you check this issue - https://github.com/matomo-org/tag-manager/issues/487?
We have fixed this and should be released with Matomo 4.11

**Comment by damzallagmythic** [comment]
Hey @AltamashShaikh I don't actually have Matomo installed on my machine at all since we are trying out Matomo cloud right now.  I've been doing everything through the tools on the website, but we did integrate the code snippet directly into the head of our website for it to work.  I don't see a way to update the tag manager being used or our account or something like that when looking at it right now.  Let me know if there is a way to update what I'm using to 4.11 on the cloud version of Matomo.

**Comment by AltamashShaikh** [comment]
Hey @damzallagmythic I understand your concern, you might have to wait for 4.11 to release and hopefully it will be released soon.

**Comment by damzallagmythic** [comment]
Sounds good thanks @AltamashShaikh .  Do you all have a rough timeline on when that will be released?

**Comment by AltamashShaikh** [comment]
@damzallagmythic 4.11 should be released by early next week and a week after that may be will plan a upgrade on cloud

**Comment by damzallagmythic** [comment]
Hey @AltamashShaikh is there any update on when this will be released on cloud?

**Comment by AltamashShaikh** [comment]
Hey @damzallagmythic We just released 4.11 and would wait for a week to check if it has any regressions before planning a release on cloud, hopefully if we don't have any issues by this week we can have it on cloud by next week may be
