### ISSUE TITLE
Add a link to the documentation about the datalayer when the container tracking code is shown

### ISSUE THREAD

**Issue by Chardonneaur** [matomo-org/tag-manager#541]
Hi guys,
It would be great to add a link to the datalayer documentation when the container tracking code is displayed.
Without it people may think that the concept of a datalayer does not exist in Matomo Tag Manager.

**Comment by snake14** [comment]
Hi @Chardonneaur ,
Thank you for taking the time to create this issue about a potential improvement. I just want to make sure that I'm understanding your recommendation. Are you thinking that it would be helpful to add a link to the datalayer documentation in this popup that displays the Tag Manager tracking code?
![image](https://user-images.githubusercontent.com/11394099/187094947-36b37af2-f9a4-49ef-b8a6-0381fbbd92e3.png)

**Comment by Chardonneaur** [comment]
Yes, exactly, nothing fancy, just a short explanation, saying that in addition to the container, one can add a datalayer in order to make data available for the tag manager to collect even more data.

**Comment by snake14** [comment]
@Chardonneaur Thank you for the clarification. Since it was a quick change, I went ahead and made it. It should be available in Matomo 4.12 forward.

**Comment by Chardonneaur** [comment]
thank you
