### ISSUE TITLE
Handle Click Events correctly in shadowDOM (web components)

### ISSUE THREAD

**Issue by multikoop** [matomo-org/tag-manager#543]
Hi!

I am facing a scenario in which ClickEvents are not handled as expected. 
See also: https://forum.matomo.org/t/event-tracking-inside-webcomponents-shadowdom/47205

After analyzing the scenario I can confirm that when a click occurs on an element (link e.g.) inside the shadowDOM the pushed event occurs on the shadowHost element and not - at least how I would expect from tracking perspective ;) - on the actual clicked element inside the shadow dom.

What is the best way to make it work as intended?

**Comment by snake14** [comment]
Hi @multikoop . Thank you for taking the time to raise this issue. I see that you created a pull request and, at a  glance, it makes sense. I'll make sure that I can reproduce the issue and test your pull request.

**Comment by multikoop** [comment]
@snake14 thanks. I am glad this fix/enhancement can be generally useful and the right analytics handling in web apps where web components are used. At least it is what I am experiencing at a current customer usecase/project. 

Short term workaround I am thinking about is maybe to create custom Tag Manager plugin including the needed fix. But somehow that approach does not feel right in the long term.

**Comment by snake14** [comment]
@multikoop Yeah. In the meantime, you could probably get what you need from the shadow DOM using a Custom JavaScript tag. Long term, I think that your fix will work well as long as it doesn't break backwards compatibility with older browsers.

**Comment by atom-box** [comment]
One user contacted us about this:

> Our Heatmaps feature is not working for LWC's(web components) and all of our screens contains LWC's(except one). I found someone posting similar issue with Web components. 
> 
> Google tag manager with similar issue and solution: [LearnExperienceCloud.com](https://www.learnexperiencecloud.com/article/Google-Tag-Manager-and-LWC-with-Shadow-DOM-for-Experience-Cloud)

**Comment by AltamashShaikh** [comment]
@atom-box May be its better to open a ticket internally for Heatmaps and reading the above blog, looks like similar code can be applied in Matomo too, replace ` window.dataLayer.push` with `window._mtm.push` and try.
