### ISSUE TITLE
Class "Piwik\Plugins\ActivityLog\Activity\Activity" not found

### ISSUE THREAD

**Issue by mattmary** [matomo-org/tag-manager#554]
Hello,

I try to generate the documentation for the developer website.

The generator parses the content of the files.
When parsing the tag manager project, it cannot resolve this class:

https://github.com/matomo-org/tag-manager/blob/485dc7c15f761d44e4ae35127502f4ea5791b3f5/Activity/BaseActivity.php#L13
![Screenshot from 2022-10-14 09-01-53](https://user-images.githubusercontent.com/86216084/195697961-3ccb2f54-a324-432b-af4d-535aa468df92.png)

So it blocks this PR https://github.com/matomo-org/developer-documentation/pull/633

**Comment by mattmary** [comment]
The tag manager submodule fetched in the https://github.com/matomo-org/matomo 4.x branch is 
`Submodule path 'plugins/TagManager': checked out '2edec7e4ba8b1ae3b7046d0e937436baaa494887'`

**Comment by snake14** [comment]
@mattmary Have you tried installing the ActivityLog plugin? I thought that plugin was installed by default, but I could be wrong.

**Comment by mattmary** [comment]
Hi @snake14 

If it is embedded in the Matomo tag manager source code, the AcitivtyLog plugin should be defined as a submodule on the Matomo branch. This is not the case for now. Did you forget it?

But for sure, I can test it with the plugin installed and tell you if it solves my problem if you tell me where I can find this plugin sources? (Can't find it so far in our repositories).

**Comment by snake14** [comment]
@mattmary That's right. I forgot that the ActivityLog plugin is part of our private repositories in the InnoCraft organisation. I didn't add that reference to the TagManager plugin though. It looks like that reference in the BaseActivity class has been there for quite some time, so I'm not sure why it's suddenly being an issue.

**Comment by mattmary** [comment]
If you don't want to add a submodule for this plugin, and you consider that the code is fine, then I would have to update my documentation generation process to load this plugin on its own.
Closing this issue, then, I'll find a solution. Thanks, @snake14

**Comment by snake14** [comment]
@mattmary Sorry about that. I don't think it can be added as a submodule since it's one of our private repositories. I messaged you in Slack about how to install the plugin in your dev environment.
