### ISSUE TITLE
"Create New ..." buttons at bottom of page can be frustrating to use

### ISSUE THREAD

**Issue by Starker3** [matomo-org/tag-manager#555]
For MTM users that have a large number of tags/triggers/variables they have to constantly scroll to the bottom of the list in order to click the "Create New" button. Doing this once or twice is okay, but for users that are often adding tags/triggers/variables it can be quite a frustrating experience.

User can use the "Dashboard" to have easier access to the Create New button, but this isn't practical if they're trying to also edit other tags at the same time since the Dashboard doesn't give much information about the existing tags.

**Comment by snake14** [comment]
Hi @Starker3 . Thank you for your suggestion. This seems pretty similar to #553 , so I'm going to link the issues and close this one.
