### ISSUE TITLE
Edit tag button produces console error with Matomo 4.12.1

### ISSUE THREAD

**Issue by jmumby** [matomo-org/tag-manager#557]
If you click the Edit Tag button within the tag manager a console error is created and no tags are shown. 

![image](https://user-images.githubusercontent.com/4339071/196845795-d1bafea6-1682-4ad7-a80c-cf57be1827a5.png)

![image](https://user-images.githubusercontent.com/4339071/196845468-62873d9c-d2e9-4b57-9010-41d21d22bbff.png)

![image](https://user-images.githubusercontent.com/4339071/196845670-a7fbe97e-5580-4e5e-af6d-decdb8082e91.png)

The issue does not happen for 4.12.0

**Comment by AltamashShaikh** [comment]
@jmumby Do you mean the issue happens for lower Matomo version or for Matomo 4.12.1?

**Comment by jmumby** [comment]
> Do you mean the issue happens for lower Matomo version or for Matomo 4.12.1?

Only for 4.12.1, this does not happen for 4.12.0. I do not have earlier versions to test.

**Comment by Starker3** [comment]
FYI I get the same issue on 4.12.1, but the error message in the console is slightly different (Possibly just the way FF shows the error):
![image](https://user-images.githubusercontent.com/20905821/196847494-a058fadf-e059-4e8e-b976-3b33b49651a9.png)

**Comment by svenlewerentz** [comment]
Same here. Can't view and edit tags, triggers and variables since update to 4.12.1. 
Preconfigured variables are still shown, but error is displayed in console here as well.

**Comment by AltamashShaikh** [comment]
Hey everyone we need to release Matomo `4.12.2` to fix this.
To fix it currently you can try this below steps
1. Check the version via this query `SELECT * FROM matomo_option where option_name='version_tagmanager'`
2. Update the `option_value` to `4.11.0` if the above query returns `4.12.0` or `4.12.1`
3. Manually run the migration by executing `./console core:update`, this should create the missing columns.

**Comment by justinvelluppillai** [comment]
FYI Matomo 4.12.2 has been released

**Comment by AltamashShaikh** [comment]
Hey everyone, Matomo 4.12.2 was released today and should fix the issue.
Closing the issue for now, please let us know here if you are still facing issues after upgrade

**Comment by svenlewerentz** [comment]
Hi, nothing changed for me. I updated to Matomo 4.12.2 and got the same errors. Tried in different browsers.

**Comment by AltamashShaikh** [comment]
@svenlewerentz Did you run `./console core:update` after the upgrade?

**Comment by svenlewerentz** [comment]
No, I used the browser based updater. I will try later and will let you know.

**Comment by svenlewerentz** [comment]
If I run console core:update the response is "Everything is up to date". 

Or should I try the steps you posted earlier?

> Hey everyone we need to release Matomo `4.12.2` to fix this. To fix it currently you can try this below steps
> 
> 1. Check the version via this query `SELECT * FROM matomo_option where option_name='version_tagmanager'`
> 2. Update the `option_value` to `4.11.0` if the above query returns `4.12.0` or `4.12.1`
> 3. Manually run the migration by executing `./console core:update`, this should create the missing columns.

**Comment by AltamashShaikh** [comment]
@svenlewerentz yes can you update version and try again ?

**Comment by svenlewerentz** [comment]
@AltamashShaikh 
It works when I performed the steps you mentioned.
![image](https://user-images.githubusercontent.com/351596/197185602-bc5decc2-8b22-401f-b464-cec98dd30cea.png)
Now tags, triggers and custom variables are listed again.

**Comment by AltamashShaikh** [comment]
Okay👍🏻

**Comment by LaurentCapelli** [comment]
Thank @svenlewerentz , Your fix works great 👍🏻  for me after updating to 4.12.2

**Comment by MatomoForumNotifications** [comment]
This issue has been mentioned on **Matomo forums**. There might be relevant details there:

https://forum.matomo.org/t/tags-and-triggers-are-no-longer-displayed/47984/3
