### ISSUE TITLE
Resolve translation key is not loaded error on "Versions" page

### ISSUE THREAD

**Issue by tsteur** [matomo-org/tag-manager#559]
<img width="1377" alt="image" src="https://user-images.githubusercontent.com/273120/198382807-f11583fc-9af2-40fd-8c93-49d1894c49b7.png">

It says

> No version found. The string TagManager_CreateNewVersionNow was not loaded in javascript. Make sure it is added in the Translate.getClientSideTranslationKeys hook.

**Comment by snake14** [comment]
Thank you @tsteur . I have merged that fix to be included in the next release.
