### ISSUE TITLE
Tel-Link with DOM-Content

### ISSUE THREAD

**Issue by GeraldJay** [matomo-org/tag-manager#57]
I tried to create a Matomo Analytics Tag for a phone link. But the trigger for "All Links Click" doesn't react. I'm not sure if this is because of the non-standard href-value or the nested DOM-structure inside the link. In the link-tag are two spans (an icon and the display text).  Is this a bug or does anyone know a way to make this work?

**Comment by tsteur** [comment]
What do you mean by "non-standard href-value"? As long as it is an `a` or an `area` element it should work. The spans within the link shouldn't cause an issue. Is there maybe any event listener that possibly stops the event (in case you are familiar with JS)?

**Comment by GeraldJay** [comment]
Sorry for the late response. 
By "non-standard href-value" I ment that "tel:..." may be filtert by some kind of validator, because only links with hrefs starting with http(s) are accepted. 
We have no additional JS attached to the link. 
I debugged the Eventhandler from the TagManager:
![image](https://user-images.githubusercontent.com/18519418/44200472-ef566780-a146-11e8-9634-93fd767902f0.png)
My problem seems to be caused by the spans inside the a-Tag. At least in the current Chrome and FF on Windows. Are you able to reproduce this?

**Comment by tsteur** [comment]
I see... so if current element is not an `A`, we would need to traverse up and check if any of its parents is a link. That's a bug and needs fixing 👍
