### ISSUE TITLE
Matomo for WP Preview Mode not showing newly created tags and triggers

### ISSUE THREAD

**Issue by VCalderoni** [matomo-org/tag-manager#580]
Hi support team, 

I'm using Matomo for WP on the DEV instance of a website, in order to learn using it and test the set up before we go live with PROD in January.  
So far it seemed to work fine: we created a PageView tag and a "Newsletter subscription" tag, and they are shown and fired correctly in Preview mode, so I'm not sure if the environment has anything to do with it. 

Issue: since today, newly created tags and triggers (such as "Click on Nav Header" and "Click on Teaser") are not shown in the "Not Yet Fired Tags" section of Preview, even if I publish the new version of the container. 
The behavior I expect would be that all set up tags and triggers show up in section "Not Yet Fired Tags" of preview mode, like it currently happens for the tags I set up before today. 

Here is a video of my screen to show you the issue: [Matomo Preview Mode - New tags not shown](https://watch.screencastify.com/v/78QYLkDyuMWXHBK4wwpG)

Can you please help me understand the origin of this issue, and how to solve it? 
Let me know if more information is necessary. 

Many thanks in advance!

**Comment by snake14** [comment]
@VCalderoni I'm sorry to hear that you are experiencing this issue. Is there any chance that your browser has cached the earlier version of the container_<container_id>_preview.js source file? Could you please try clearing your browser's cache and doing a hard refresh on the preview page?

**Comment by VCalderoni** [comment]
@snake14 Hey Jacob, thanks for the suggestion, that actually worked. I'll see if that will be necessary every time we create new tags, hopefully not. 
This is already another topic, sorry for asking here, but: now that I could test the tags, I noticed that the list of fired events gets refreshed and reset every time a new page loads. The log also keeps track only the last 6 events. I couldn't find a way to see a history of all events that triggered by page. Is this expected behavior? Many thanks in advance for your help!

**Comment by snake14** [comment]
@VCalderoni I'm glad that worked for you. I don't think that should be necessary all of the time as I don't recall having to do that as part of my testing.

I'm not sure why it would only be keeping 6 events. I was just testing and the list of events on the left site grew to over 40. Of course, in the advanced settings of my tags, I have the fire limit set to `Unlimited` you might want to check if you have yours set to something more restrictive. You might also try searching the Matomo forum for more information.
![image](https://user-images.githubusercontent.com/11394099/206294711-a44f3d66-35f3-4564-a806-df32833b2fab.png)


As the original issue has been resolved, I'm going to close this issue. Please let me know if you feel it needs to be reopened.
