### ISSUE TITLE
Allow user to set disableAlwaysUseSendBeacon to prevent ping request and getting blocked by uBlock

### ISSUE THREAD

**Issue by ghost** [matomo-org/tag-manager#581]
At the moment it is not possible to set disableAlwaysUseSendBeacon to prevent ping requests.
This causes adblockers to prevent tracking.

![Auswahl_004](https://user-images.githubusercontent.com/1035170/206142716-2cef7b4c-b17c-4096-b546-f5431bbb5f28.png)
![Auswahl_003](https://user-images.githubusercontent.com/1035170/206142717-558cca02-cdc3-4274-99b1-7cf56f1ef780.png)
![Auswahl_002](https://user-images.githubusercontent.com/1035170/206142721-cf83c96d-d6ca-4ee9-b881-e5bf8bb2418a.png)

sghiel from matomo tracker was kind enough to point me to this repository.
https://github.com/matomo-org/matomo/issues/19864#issuecomment-1340640583

Do you possibly have a suggestion for a workaround that I can set the parameter?
Currently, only alwaysUseSendBeacon can be set in the interface.

Thank you very much in advance.

**Comment by ghost** [comment]
As a temporary solution I have changed two files.

Template/Variable/MatomoConfigurationVariable.php
```php
            $this->makeSetting('disableAlwaysUseSendBeacon', false, FieldConfig::TYPE_BOOL, function (FieldConfig $field) {
                $field->title = Piwik::translate('TagManager_MatomoConfigurationMatomoDisableAlwaysUseSendBeaconTitle');
                $field->description = Piwik::translate('TagManager_MatomoConfigurationMatomoDisableAlwaysUseSendBeaconDescription');
            }),
```

Template/Tag/MatomoTag.web.js
```javascript
                    if (matomoConfig.disableAlwaysUseSendBeacon) {
                        tracker.disableAlwaysUseSendBeacon();
                    }
```

Translation is missing, but not necessary for the usage.
TagManager_MatomoConfigurationMatomoDisableAlwaysUseSendBeaconTitle and TagManager_MatomoConfigurationMatomoDisableAlwaysUseSendBeaconDescription

**Comment by snake14** [comment]
Hi @Orgoth . Thank you for taking the time to create this issue. Probably the easiest workaround would be to, in your Matomo Tag Manager dashboard, create a Custom HTML tag and call the disableAlwaysUseSendBeacon tracker method in that.

Thank you. Your second comment looks like a good improvement suggestion. I will add this issue to our list of issues to be prioritised by our product team.

**Comment by EPNW-Eric** [comment]
So, the "temporary solution" seems pretty solid, why didn't you open a PR?

**Comment by ghost** [comment]
I had a silent hope that it would be adopted by contributors or authors since it is such a simple and easy customization.

Another point was still, currently there is the following point in the system.
"MatomoConfigurationMatomoAlwaysUseSendBeaconTitle": "Always use sendBeacon",
With the introduction of my workaround, the end user would question why there is the additional item to disable.
If he has disabled the first entry "Always use sendBeacon"?! "unchecked"

The other side is then still the effort with all the points that must be met for the contribution before.

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

**Comment by snake14** [comment]
Thank you @Orgoth for creating that PR. It was been merged and will be included in the next Matomo 5.x release.
