### ISSUE TITLE
how to write my own code in container_**.js file when it create

### ISSUE THREAD

**Issue by kkm8257** [matomo-org/tag-manager#589]
I am a developer using Matomo Tag Manager.

Every time I add a new tag and "publish" it seems that the "/piwik/js/container_000.js" file is overwritten with the updates.

I want to plant the code I want in the overwritten part.

It seemed to me that "/piwik/js/container_000.js" is being created based on the "/piwik/js/piwik.js" file.

So I planted the code I wanted in the "/piwik/js/piwik.js" file ( function name is sendPostRequestViaSendBeacon() ),
but it was not added to "/piwik/js/container_000.js" when tag manager is published.

May I know how I can control the container_000.js file?

**Comment by AltamashShaikh** [comment]
@kkm8257 You shouldn't edit `container.js` if you want to place you additional HTML code, please make use of CustomHTML tag, for more details refer this training [video](https://matomo.org/tag-manager-training/) no 05 (Tags)

**Comment by heurteph-ei** [comment]
@kkm8257 
Does the following plugin meet your needs?
https://plugins.matomo.org/JsTrackerCustom

**Comment by AltamashShaikh** [comment]
@kkm8257 can we close this issue ?
