### ISSUE TITLE
Matomo publish wrong version of container

### ISSUE THREAD

**Issue by xSimekj1** [matomo-org/tag-manager#590]
When publishing new container version, it does get created, and published in Matomo dashboard, but once user visit the page an old version of container is provided. 
This looks like caching problem, so I turned off caching plugins, but the issue stays. (Clear Matomo Cache in diagnostics also does not help with this).
I tried to get back to multiple older versions and it looks like the output versions on client side are somehow stuck between 1.0.2 , 1.0.9 and 1.0.13 - so maybe wrong version name is saved into database, while publishing new container version?

Example of current version: 1.0.19
![image](https://user-images.githubusercontent.com/28231910/212538437-6aaa7279-6524-42c7-9e42-37ecbea78187.png)
Version used on page: 1.0.13
![image](https://user-images.githubusercontent.com/28231910/212538503-961f1b48-5b75-4975-ad58-3464e201e96e.png)

**Comment by AltamashShaikh** [comment]
@xSimekj1 It can be browser cache, did you try clearing that ?

**Comment by xSimekj1** [comment]
@AltamashShaikh confirming this. 
I cleared the cache and also tried to clear all browsing data in my browser (chrome), I also tried incognito mode or visit via different browser (Firefox) to test if its a browser problem, result is always the same.
I was testing switching to older versions and back, still getting wrong version (now 1.0.2 instead of 1.0.19), I wonder if there can be issue with saving new current versions into database.

**Comment by AltamashShaikh** [comment]
@xSimekj1 do you have any url where we can check this?

**Comment by xSimekj1** [comment]
You can test the frontend part in console right on production site, I sent you direct reply via email

**Comment by AltamashShaikh** [comment]
@xSimekj1 Its your CDN which is caching the JS
Current URL being loaded: `https://{YOUR_DOMAIN}/wp-content/uploads/matomo/container_9f9k7hp2.js` which is cached at your CDN level.
Now if you add any query parameter to break the cache
`https://{YOUR_DOMAIN}/wp-content/uploads/matomo/container_9f9k7hp2.js?ver=xSimekj1` and compare the output you will see the difference like this

left side is the cached version and right side is the newer one
![Screenshot from 2023-01-16 18-48-37](https://user-images.githubusercontent.com/14902277/212688020-98339482-5072-4418-bb47-04624212722b.png)

**Comment by AltamashShaikh** [comment]
The new cached has the proper version to `1.0.19`
![Screenshot from 2023-01-16 18-54-11](https://user-images.githubusercontent.com/14902277/212688587-8bd782fd-36ba-4efe-9f66-60940ef4681b.png)
