### ISSUE TITLE
Tag Manager container doesn't delete containers when Website is deleted

### ISSUE THREAD

**Issue by Starker3** [matomo-org/tag-manager#595]
Issue is as described in the title, it seems that the container is not always deleted when the website has been deleted.

We encountered this when a Cloud customer encountered a quota issue and we confirmed that some containers existed for ID Sites that no longer existed in the database.

**Comment by tsteur** [comment]
Random guess maybe there was an issue removing files and then the container was never deleted in that logic here: 
<img width="860" alt="image" src="https://user-images.githubusercontent.com/273120/214477007-435a5845-48f0-4d25-bb1c-3bc192f05c0a.png">
Eg cloud might delete many s3 files and there could be issues around that

**Comment by tsteur** [comment]
Actually, sorry, that is not the case as related tags for deleted sites still exist too. So the logic here didn't run.

**Comment by Starker3** [comment]
Refs `CLOUD-1226`

**Comment by AltamashShaikh** [comment]
@tsteur I tested the delete behaviour with 2 sites and it seems to delete the files properly, do I need to check something specific or its an issue omly with cloud ?

Before delete
![Screenshot from 2023-01-25 12-25-24](https://user-images.githubusercontent.com/14902277/214499626-0f220733-c325-4953-817a-fe74d2e543c1.png)


After delete
![Screenshot from 2023-01-25 12-25-42](https://user-images.githubusercontent.com/14902277/214499590-1c29701e-6795-4c95-94d1-b67210b9d3d4.png)

**Comment by tsteur** [comment]
FYI We're fixing the quota problem on Cloud so this might make this one bit less important.

@AltamashShaikh I'm assuming it's edge cases where some other event listener in some other plugin might error for some reason or something and then it's not working.

Potentially we would eventually need to also have a scheduled task to delete containers etc that weren't removed by this hook.

**Comment by AltamashShaikh** [comment]
Yes we can have a task to delete the files of deleted container
