### ISSUE TITLE
Hide Tag Manager Section

### ISSUE THREAD

**Issue by goochj03** [matomo-org/tag-manager#602]
We have had a customer ask about hiding the Tag Manager section for users that have '**View**' access.
Currently users with **View** access can access the Tag Manager and see the Tag/triggers that are in place. (they cannot proceed to edit or see the contents of the tags/triggers.) 

However it has been requested if it's possible to implement an option that could be set to 'hide' the Tag Manager section completely (if the super user has chosen too) if a user has **View** access.

Comment from customer: ": how can we give View Access to a Matomo dashboard to somebody without giving them view access of Tag Manager as well? As of right now, whenever we sent view access to our clients, they can also see the Tag Manager section, which we would want to avoid."

**Comment by goochj03** [comment]
Have had another customer requesting a similar feature, "Is it possible to hide certain functions in Matomo for certain users? i.e some users should not see E-Commerce, Funnels, Tag Manager etc"

**Comment by AltamashShaikh** [comment]
cc: @Stan-vw

**Comment by goochj03** [comment]
Another request for hiding the Tag Manager section "Is there a way to remove access to Tag Manager to users with "**View**" access rights ? We want to grant access to our customer to the portal without showing the tag manager menu. Is it possible to change the setup in order to do that ?"

**Comment by heurteph-ei** [comment]
@goochj03 
Do you host Matomo on several servers?
**Maybe** you could dedicate one of them for customers in order to see data. And on this dedicated server, do not install the MTM plugin... **I don't know if this could work?**

**Comment by Stan-vw** [comment]
Suggested design in the General settings, open to feedback:
![image](https://github.com/user-attachments/assets/b9434710-12c9-4cb7-be13-04ce5c6ef7a2)

**Comment by snake14** [comment]
The new setting should be available as part of the next release of Matomo.
