### ISSUE TITLE
Problem! matomo is tracking actions and events into two session. 

### ISSUE THREAD

**Issue by areeshaad** [matomo-org/tag-manager#605]
Hi there, 
After creating some tags and triggers, the report "Visits in real-time" is dividing actions(pageviews) and trigger events into two separate sessions. 
Here is an example,
![image_2023_03_04T08_00_37_598Z](https://user-images.githubusercontent.com/98154363/222885224-7f4f2006-6667-4f7e-832e-f0dd54db9494.png)
Although the user is same and the browser is also same yet it is creating two sections at the same time. I want the default behaviour. For example, a mixed session (actions and events) for one user at a time.
![dashboard](https://user-images.githubusercontent.com/98154363/222885454-fefc966b-32bb-4c00-ad71-34dc5e9fee2b.jpg)

 Please help me or guide me to fix this problem. I would be greatly thankful for the time and consideration.

**Comment by snake14** [comment]
Hi @areeshaad . Thank you for taking the time to create this issue. Unfortunately we don't answer questions in this issue tracker but only handle feature requests or bug reports. It'd be great if you can ask the question in our forum: https://forum.matomo.org/ .

That said, I most commonly see events divided like that when there are [custom dimensions](https://matomo.org/guide/reporting-tools/custom-dimensions/) defined. Once that visit is archived, you can view it in the Visits Log. Those actions will likely be grouped under the same visitor profile, but possibly shown as separate visits do to the way custom dimensions were segmented. I hope that helps.
