### ISSUE TITLE
Optional SRI hash for tracking code

### ISSUE THREAD

**Issue by 9joshua** [matomo-org/tag-manager#621]
Provide the option to include an SRI hash value to Tag Manager tracking code. This would provide added security in the event the referenced JS files are compromised/altered.

Example:
```HTML
<!-- Matomo Tag Manager -->
<script>
var _mtm = window._mtm = window._mtm || [];
_mtm.push({'mtm.startTime': (new Date().getTime()), 'event': 'mtm.Start'});
var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
g.async=true;
g.src='http://localhost/matomo/js/container_jFkRDfNd.js';
g.integrity='sha384-5Xln6t2vW7GaQP3Y+TM2XlxVTNwatctZrKjbcYeBMXtmxKHOs+ipocJK6ejUllcH';
s.parentNode.insertBefore(g,s);
</script>
<!-- End Matomo Tag Manager -->
```

For Cloud this would also require serving files with CORS headers, which doesn't currently appear to be the case.

**Comment by AltamashShaikh** [comment]
@9joshua I am not sure this could be doable, as the content of the file could change and so would the hash and that might not work post that change and the user would have to keep changing constantly

**Comment by 9joshua** [comment]
@AltamashShaikh You are probably right. It would be just as easy to create the hash with every Tag update using this (so long as you remember to update with every Tag manager change):
`curl -o temp.js https://example.com/matomo.js && openssl dgst -sha384 -binary temp.js | openssl base64`

Cloud CORS headers currently prevent integrity checks but I have made a separate issue for that. Closing this.
