### ISSUE TITLE
Add a field for setSessionCookieTimeout within the matomo configuration variable

### ISSUE THREAD

**Issue by Chardonneaur** [matomo-org/tag-manager#624]
Hi Team,

I got a client of mine today asking for a setSessionCookieTimeout field within the Matomo configuration variable.
Is it possible to do it?
_paq.push(['setSessionCookieTimeout', timeoutInSeconds=1800])

**Comment by snake14** [comment]
Hi @Chardonneaur . It doesn't look like that particular config is supported by `_mtm.push` and using `_paq.push` in conjunction with MTM isn't always reliable. The two workarounds that I can think of are putting that `_paq.push` call in a CustomHTML tag or putting it in an event listener that waits till the page has loaded. Putting the JS in a custom tag is probably the more reliable option as it ensures the the MTM JS has loaded before the tag is executed. There's an example in a [FAQ about eCommerce](https://matomo.org/faq/tag-manager/faq_35847/) and MTM, but that's more advanced than what your customer needs. You'd probably only need to worry about Step 3 in the FAQ and replace the code inside the script tags with `_paq.push(['setSessionCookieTimeout', timeoutInSeconds=1800])`.

I'm closing the issue, but please let me know if you have any further questions.

**Comment by snake14** [comment]
It looks like this setting was added to the Matomo config variable not too long ago:
![image](https://github.com/user-attachments/assets/2cbb71ab-b9d7-48d8-aa46-d385bd33cddf)
