### ISSUE TITLE
Is there a way to detect if a pageview is the first pageview in a visit?

### ISSUE THREAD

**Issue by tomper00** [matomo-org/tag-manager#626]
I would like to set up som logic that only fires on the first pageview in a visit. 
My first idea was to set up a variable that reads and stores data in the session storage (browser).
sessionStorage.setItem("myvar", "test");
sessionStorage.getItem("myvar");

However the session storage is not related to a Matomo session (it relates to the web server) so it wont work out of the box.

Any suggestions on how this could be achieved?

**Comment by AltamashShaikh** [comment]
@tomper00 There is nothing present which matches your need, you can try checking on your server/client if you have any cookie set(not sure if this will work you need to try) ?
`_pk_id.{sitedID}.*` is the pattern so you need to check if a cookie with this pattern name exists, if doing on client site try to check before Matomo is called
