### ISSUE TITLE
Debug mode

### ISSUE THREAD

**Issue by nbsoledis** [matomo-org/tag-manager#627]
Hello,

I tried numerous solutions in order to open the debug view (windows) but i don't have access to it. I followed the documentation and the differents guidelines but nothing is working.. I tried on Google Chrome, without adblocker, with a debug mode, by emptying the cache... Nothing appears. Can you help me to activate the debug mode pls, i encounter a problem with a user id and it's hard to understand without this functionnality.

Best regards,

![image](https://github.com/matomo-org/matomo/assets/133791071/df709f38-e596-49eb-96f9-267e6fef0670)
![image](https://github.com/matomo-org/matomo/assets/133791071/0dc03941-4050-44c2-b894-fa8ecd06b84d)

**Comment by AltamashShaikh** [comment]
@nbsoledis Can't see any Matomo Tag Manager code on https://www.cuisibane.com/ can you check if the code is installed correctly ?

**Comment by nbsoledis** [comment]
Hello,

We are using a Prestashop addon. The tracking is working, the data is correctly dispashed on the dashboard.

De : Altamash Shaikh ***@***.***>
Envoyé : mardi 16 mai 2023 19:57
À : matomo-org/tag-manager ***@***.***>
Cc : Nicolas BERTHELOT ***@***.***>; Mention ***@***.***>
Objet : Re: [matomo-org/tag-manager] Debug mode (Issue #627)


@nbsoledis<https://github.com/nbsoledis> Can't see any Matomo Tag Manager code on https://www.cuisibane.com/ can you check if the code is installed correctly ?

**Comment by AltamashShaikh** [comment]
@nbsoledis I don't think we manage this addon and I can see this addon is loading the JS code on your site not the Matomo tracking code which is different from the Javascript code. You can read more about installing the Matomo tag manager code [here](https://matomo.org/faq/tag-manager/install-a-tag-manager-container-on-your-site/)

**Comment by nbsoledis** [comment]
If I install the code, I will have double tracking on the website..
The addon is used for the e-commerce tracking.

De : Altamash Shaikh ***@***.***>
Envoyé : mercredi 17 mai 2023 09:08
À : matomo-org/tag-manager ***@***.***>
Cc : Nicolas BERTHELOT ***@***.***>; Mention ***@***.***>
Objet : Re: [matomo-org/tag-manager] Debug mode (Issue #627)


@nbsoledis<https://github.com/nbsoledis> I don't think we manage this addon and I can see this addon is loading the JS code on your site not the Matomo tracking code which is different from the Javascript code. You can read more about installing the Matomo tag manager code here<https://matomo.org/faq/tag-manager/install-a-tag-manager-container-on-your-site/>

**Comment by AltamashShaikh** [comment]
@nbsoledis Seeing this, looks like it supports only Matomo JS tracking and I am afraid  we can't help you much with the addon
![image](https://github.com/matomo-org/tag-manager/assets/14902277/609070a6-e621-4fcc-81ea-318129bb2ee6)
