### ISSUE TITLE
Getting an error when using 'setVisitorCookieTimeout'

### ISSUE THREAD

**Issue by andradeje** [matomo-org/tag-manager#653]
Hello, as you can see i m getting an error when using 'setVisitorCookieTimeout'
![image](https://github.com/matomo-org/tag-manager/assets/56430752/d0cb192e-5b04-4d61-b9d9-1eced2305324)

Can you tell me if there is something wrong in my script or if its not working for the moment when we are using  Matomo Tag Manager ?

```
var _mtm = window._mtm = window._mtm || [];
_mtm.push({'mtm.startTime': (new Date().getTime()), 'event': 'mtm.Start'});
_mtm.push(['setVisitorCookieTimeout', 15768000]); // _pk_id set to 6 month

var d = document, g = d.createElement('script'), s = d.getElementsByTagName('script')[0];
g.type = 'text/javascript';
g.async = true;
g.src = 'https://cdn.matomo.cloud/mitrust.matomo.cloud/container_xxxxxx.js';
s.parentNode.insertBefore(g, s);
```

**Comment by AltamashShaikh** [comment]
@andradeje Please set the customCookieTimeout using the Matomo Configuration Variable
![Screenshot from 2023-06-27 17-37-10](https://github.com/matomo-org/tag-manager/assets/14902277/8d75e945-f0dd-4453-8d70-a5a22ef7e5dc)
