### ISSUE TITLE
Tag-Manager script declares variables in global context

### ISSUE THREAD

**Issue by Mercutio42** [matomo-org/tag-manager#654]
Tag-Manager script declares variables in global context and might collide with other scripts

<script>
var _mtm = window._mtm = window._mtm || [];
_mtm.push({'mtm.startTime': (new Date().getTime()), 'event': 'mtm.Start'});
var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
g.async=true; g.src=''; s.parentNode.insertBefore(g,s);
</script>

error:
identifier 'd' ('g','s') has already been declared 

might apply IIFE
(function(){
var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
g.async=true; g.src=''; s.parentNode.insertBefore(g,s);
})();

**Comment by snake14** [comment]
Hi @Mercutio42 . Thank you for taking the time to create this issue. It looks like using an [IIFE](https://developer.mozilla.org/en-US/docs/Glossary/IIFE) to insert the MTM script would be a good way to avoid polluting the global scope. Thank you for the excellent suggestion. I will mark this issue to be prioritised by our Product team.

**Comment by heurteph-ei** [comment]
Then the same for standard JavaScript tracking bootstrap code ;-)

**Comment by snake14** [comment]
Thank you for mentioning the regular JavaScript tracking code @heurteph-ei . I'm not sure when, but it appears to have already been removed from the global scope:
![image](https://github.com/matomo-org/tag-manager/assets/11394099/15a4e1fa-df7e-4b27-af37-dd0113da4cbc)

**Comment by snake14** [comment]
@Mercutio42 I went ahead and updated the Matomo Tag Manager code snippet while I was working on some other improvements in MTM. The changes were included in the Matomo 4.15.0 release.
