### ISSUE TITLE
Tracking URLs in lowercase (inside the Tag Manager container) 

### ISSUE THREAD

**Issue by marcriudalbas** [matomo-org/tag-manager#660]
We have created a container in the tag manager to be able to track different stages (dev, test, prod).

The problem is that Matomo saves as different tracks/sites the same URL in different cases of uppercase and lowercase. 

* See example below:

![image](https://github.com/matomo-org/tag-manager/assets/14929281/bbe63ec6-10ea-491f-956d-b1e8c8386658)

As stated in the FAQ: https://matomo.org/faq/how-to/faq_90/ it would be enough to set the line `_paq.push(['setCustomUrl', location.href.toLowerCase()]);` before the line `_paq.push(['trackPageView']);`

However, when working with the track manager and a container for staging, the code in the script block looks like this:

```html
    <script>
      var _mtm = window._mtm = window._mtm || [];
      _mtm.push({'mtm.startTime': (new Date().getTime()), 'event': 'mtm.Start'});
      var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
      g.async=true; g.src='<%= VUE_APP_MATOMO_SCRIPT_URL %>'; if ('<%= VUE_APP_MATOMO_SCRIPT_URL %>' !== 'NULL') s.parentNode.insertBefore(g,s);
    </script>
```

So there is no way to set the line `_paq.push(['setCustomUrl', location.href.toLowerCase()]);`, because the track happens inside the container.

Is there still a way to track every site as lowercase?

Thanks in advance!

**Comment by heurteph-ei** [comment]
Hi @marcriudalbas 
This kind of issue should be post in the Matomo forum: https://forum.matomo.org/

Your problem can be solved by:
1. Create a **Custom JavaScript variable** (eg. called _cleanedUrl_):
```
function () { return location.href.toLowerCase(); }
```
2. Edit the PageView **Matomo Analytics tag** and set **Custom URL** to the previously created **Custom JavaScript variable** (eg. _cleanedUrl_)

**Comment by marcriudalbas** [comment]
Hello @heurteph-ei 

Thanks for the quick reply and the detailed explanation.

This seems to do the trick. Maybe it would make sense to include this in the documentation or the FAQs for users using MTM.
