### ISSUE TITLE
Debug function doesn't work

### ISSUE THREAD

**Issue by guilletmarion** [matomo-org/tag-manager#661]
When trying to use debug mode, nothing happens, even after a "Ctrl+Shift+R"

As you can see on this video : https://www.loom.com/share/8d0215f4bfca4468a4193b6f5f7dc4a3?sid=fad7e8b2-4417-4d36-8f25-dc4d55f58d6e

**Comment by AltamashShaikh** [comment]
@guilletmarion Is it possible to share the URL on which debug view is not visible ?

**Comment by AltamashShaikh** [comment]
@guilletmarion I see that you have integrated JS tracking code and not Matomo Tag Manager tracking code.

![Screenshot from 2023-07-18 21-12-50](https://github.com/matomo-org/tag-manager/assets/14902277/511b4f7e-43dd-47cf-ba36-a7d23ad2d0b2)


You can follow this [guide](https://matomo.org/faq/tag-manager/install-a-tag-manager-container-on-your-site/) on how to install Matomo Tag Manager code.

I am closing this issue, feel free to re-open if it still doesn't work

**Comment by guilletmarion** [comment]
ok thank you for your response
