### ISSUE TITLE
[Enhancement] Add option to NOT copy from Google dataLayer when loading Matomo datalayer (_mtm)

### ISSUE THREAD

**Issue by peterbo** [matomo-org/tag-manager#662]
On a page using both, Google dataLayer and Matomo datalayer, we're experiencing major problems with this functionality. We're using different ecommerce-object definitions, and mostly, the explizit variable values of _mtm are overridden with the google dataLayer values.

That causes _mtm to display the correct values in the browser console, but MatomoTagManager.dataLayer.get('ecommerce'); (which is used internally) to use the wrong data (which was copied over from google dataLayer).

**Comment by AltamashShaikh** [comment]
@peterbo So sorry to hear that you are facing this issue, I have added this issue for priortisation our product team will check and schedule it accordingly.

**Comment by AltamashShaikh** [comment]
@peterbo We might need to make this [code](https://github.com/matomo-org/tag-manager/blob/4.x-dev/javascripts/tagmanager.js#L1820..L1827) optional to solve your problrm

**Comment by peterbo** [comment]
Hello @AltamashShaikh! 
> We might need to make this [code](https://github.com/matomo-org/tag-manager/blob/4.x-dev/javascripts/tagmanager.js#L1820..L1827) optional to solve your problrm

Yes, that's exactly the code that should be configurable (e.g. enable / disable Google dataLayer compatibility mode in the Matomo Configuration Variable of the TagManager). 

Thank you!

**Comment by snake14** [comment]
@peterbo We weren't able to make the configuration at the variable level, since there can be many variables per window, but we were able to make it work at the container level. I just merged the PR and the changes should be included in the release of Matomo 5

**Comment by peterbo** [comment]
@snake14 - Great, thank you!!

>We weren't able to make the configuration at the variable level

I think that's fine. I can't think of real use-cases where you'd need more functionality than "on" or "off".
