### ISSUE TITLE
Ability to enable/disable elements

### ISSUE THREAD

**Issue by matmicro** [matomo-org/tag-manager#663]
As a Matomo Tag Manager, i would like to be able to enable/disable whenever i want a balise, a trigger.
Currently the only ay is to delete it, which is not convenient.

Can this be added easily ?

Regards

**Comment by snake14** [comment]
Hi @matmicro . Thank you for taking the time to create this issue. It seems fairly similar to issue #23 . I think we can go ahead and link this to that issue and close it.
