### ISSUE TITLE
HeartBeat timer in matomo tag manager

### ISSUE THREAD

**Issue by Chardonneaur** [matomo-org/tag-manager#666]
Hello,
would it be possible to set the duration of the timer within the heartbeat timer feature of Matomo Tag Manager?

**Comment by snake14** [comment]
Hi @Chardonneaur . Looking at the code, it appears that Tag Manager only uses the default setting for the heartbeat timer, which I believe is 15 seconds. You could probably use `_paq.push(['enableHeartBeatTimer', {desired_number_over_5}]);` inside of a CustomHtml tag. Will that work or would you like me to add this for prioritisation as an enhancement?

**Comment by Chardonneaur** [comment]
Thank you @snake14, well i think that could be a great enhancement for any features of the tag manager where a value can be entered as an additional option.

**Comment by snake14** [comment]
Sounds good. I'm marking this as an enhancement to be prioritised.

Just to add more detail to help with the prioritisation process, we're talking about adding an optional field where the customer can set the number of seconds when the Enable HeartBeat Timer checkbox is checked in a Matomo configuration Variable:
![image](https://github.com/matomo-org/tag-manager/assets/11394099/9f68d8af-e9f9-4942-8770-050d954d0767)

**Comment by Chardonneaur** [comment]
Yes exactly, the idea would be to have the same level of customization within the Matomo configuration variable than on a custom tracking code.

**Comment by EPNW-Eric** [comment]
Anyone working on this yet? If not, I'd like to try implementing it 😃.

**Comment by AltamashShaikh** [comment]
@EPNW-Eric Feel free to work on this :+1:

**Comment by heurteph-ei** [comment]
I thought the HeartBeat was no more a ping request, but has been replaced by the sendbeacon at page unload... Am I wrong?

**Comment by AltamashShaikh** [comment]
@heurteph-ei Thanks for the info, I just checked with the core team and what you are saying seems to be correct.
https://github.com/matomo-org/matomo/issues/15612#issuecomment-664615366
@EPNW-Eric Can we please remove the configuration from the PR ?

**Comment by EPNW-Eric** [comment]
Hm, even if @heurteph-ei is correct with respect to the `unload`-event, the `configHeartBeatDelay` is still used in calculations to determin wheter to send a ping or not:

https://github.com/matomo-org/matomo/blob/d58c2ab0328ff9189e43cdd1ea31559e0d563d90/js/piwik.js#L2951-L2957

https://github.com/matomo-org/matomo/blob/d58c2ab0328ff9189e43cdd1ea31559e0d563d90/js/piwik.js#L4070-L4085

So I think that, since it is still used, it should still be configurable.

**Comment by AltamashShaikh** [comment]
@bx80 @sgiehl  do you see any issue in having Heartbeat configurable?

**Comment by bx80** [comment]
@AltamashShaikh Isn't it [already configurable](https://github.com/matomo-org/matomo/blob/783216108690c0f417982898e84071e38d4d361c/js/piwik.js#L6511) when enabling the heartbeat with `_paq.push(['enableHeartBeatTimer', 30]);` ?

**Comment by AltamashShaikh** [comment]
@bx80 Thanks for confirming, @EPNW-Eric lets not change it then

**Comment by EPNW-Eric** [comment]
Wait, I'm confused now.

> @AltamashShaikh Isn't it [already configurable](https://github.com/matomo-org/matomo/blob/783216108690c0f417982898e84071e38d4d361c/js/piwik.js#L6511) when enabling the heartbeat with `_paq.push(['enableHeartBeatTimer', 30]);` ?

Yes it is possible, but not using a the Tag Manager and a Matomo Configuration Variable. 

The whole purpose of this issue and PR #679 is to add the options that are already configurable with JavaScript to the Tag Managers UI.

So @AltamashShaikh do you mean "not change it then" in a sense of "keep the current state of the PR" or as in "remove if from the PR and keep the current behavior (=not configurable from the Tag Manager UI)" ?

**Comment by AltamashShaikh** [comment]
@EPNW-Eric Sorry for the confusion, I meant keep your changes as it is

**Comment by EPNW-Eric** [comment]
Since #679 is merged now, I think this issue can be closed 😃.
