### ISSUE TITLE
Matomo preview shows an empty board

### ISSUE THREAD

**Issue by guilletmarion** [matomo-org/tag-manager#667]
Quand je clique sur le bouton "Debug" de l'interface du Tag Manager de Matomo, j'accède à mon site avec un panneau ouvert, mais vide.
Rien ne change si je fais Ctrl+shift+R.

![image](https://github.com/matomo-org/tag-manager/assets/57708683/1b3896a5-891c-42a6-b28a-1d263b0c0568)

**Comment by guilletmarion** [comment]
PS : J'ai désactivé tous mes adblocker et ai essayé sur plusieurs navigateurs dont Chrome, Firefox et Brave. En mode classique ou en mode inconnu. Rien n'y fait.

**Comment by snake14** [comment]
Hi @guilletmarion . I'm sorry that you are experiencing this issue. Have you looked at the [FAQ about troubleshooting MTM debug mode](https://matomo.org/faq/tag-manager/why-is-debug-console-not-loading-for-me/)? Another place you could check is the [Matomo forum](https://forum.matomo.org/). As mentioned in [this forum thread](https://forum.matomo.org/t/issue-with-matomo-tag-manager-debug-mode/50447), you could try opening the browser's JavaScript console (F12 in most browsers) and see if there are any errors. I'm going to go ahead and close this issue, but please feel free to reach back out and let us know if you find a bug in the application.
