### ISSUE TITLE
Matomo preview shows an empty board

### ISSUE THREAD

**Issue by guilletmarion** [matomo-org/tag-manager#673]
Bonjour,
J'ouvre ce nouveau ticket suite à la clôture un peu rapide du ticket https://github.com/matomo-org/tag-manager/issues/667

J'ai bien consulté la FAQ ainsi que le forum, c'est pour cela que je précisais "PS : J'ai désactivé tous mes adblocker et ai essayé sur plusieurs navigateurs dont Chrome, Firefox et Brave. En mode classique ou en mode inconnu. Rien n'y fait."

En analysant la console développeur, je ne trouve aucune erreur liée à Matomo

![image](https://github.com/matomo-org/tag-manager/assets/57708683/b6e31feb-200d-444f-a876-36e466daf0c9)

**Comment by snake14** [comment]
Hi @guilletmarion . I'm sad to see that you're still experiencing this issue. If you're using Matomo Tag Manager, the JS file that loads would be named `container_{container_id}`.
![image](https://github.com/matomo-org/tag-manager/assets/11394099/88ee6d34-52c1-4432-bd8e-72594bbde09d)

If that file appears to load correctly, do you see any JavaScript errors in the `Console` tab?
![image](https://github.com/matomo-org/tag-manager/assets/11394099/82669264-67cc-405d-b601-be6638927555)

**Comment by AltamashShaikh** [comment]
@guilletmarion The preview mode doesn't load due to your CSP rule

![Screenshot from 2023-08-17 07-10-51](https://github.com/matomo-org/tag-manager/assets/14902277/93941f8e-29a6-45fc-b7e0-728ab71fa753)

If we disable CSP for your page, I can see the debug mode loading as expected

![Screenshot from 2023-08-17 07-12-01](https://github.com/matomo-org/tag-manager/assets/14902277/60878cbd-d70e-4e94-a070-fb4c802991c4)

**Comment by guilletmarion** [comment]
Ok thank you.
We'll fix this error then.
Until then, how did you disable CSP from your browser ?

**Comment by AltamashShaikh** [comment]
@guilletmarion You can check this [link](https://intercom.help/designfiles/en/articles/4684029-disabling-content-security-policy) on how to disable CSP

**Comment by guilletmarion** [comment]
Thank you very much. I close the issue

**Comment by AltamashShaikh** [comment]
@guilletmarion Just FYI there is an error in the implemntation
```
The method setTrackerUrl is registered more than once in "_paq" variable. Only the last call has an effect. Please have a look at the multiple Matomo trackers documentation:

VM121 container_s4n03ZE1_preview.js:187 The method setSiteId is registered more than once in "_paq" variable. Only the last call has an effect. Please have a look at the multiple Matomo trackers documentation
```
You are calling this methods more than once, so I would recommend you to check your implementation properly
