### ISSUE TITLE
Switch to temporary disable a tag

### ISSUE THREAD

**Issue by alexlehm** [matomo-org/tag-manager#683]
I was testing something with the migration of Google Analytics to the new GA4 type and I thought it would be useful to be able to disable a specific tag temporarily. there is no option for that as far as I checked.
I worked around that by enabling the tag on Pageview and disabling it on Pageview, this seems to have the effect, but a specific switch would be helpful.

**Comment by snake14** [comment]
Hi @alexlehm  . Thank you for taking the time to create this issue. It seems fairly similar to issue #23 . I think we can go ahead and link this to that issue and close it.

**Comment by alexlehm** [comment]
sorry, i didn't find that issue when searching for similar ones

**Comment by snake14** [comment]
No worries @alexlehm . The titles were different enough that it took me a little while to find it.
