### ISSUE TITLE
Add a line for the cookie session within the Matomo configuration variable

### ISSUE THREAD

**Issue by Chardonneaur** [matomo-org/tag-manager#690]
Hi Team,
currently within the matomo configuration variable, there is an option to set the duration of the visitor cookie but not for the session cookie.
Would it be possible to add it?
Thank you,

**Comment by AltamashShaikh** [comment]
@Chardonneaur Its already done via #679 - https://github.com/EPNW/tag-manager/blob/5.x-dev/Template/Tag/MatomoTag.web.js#L287 and should be part of Matomo 5
