### ISSUE TITLE
When activating TagManager - Overlay plugin is required

### ISSUE THREAD

**Issue by mikkeschiren** [matomo-org/tag-manager#693]
In our setup Overlay plugin is deactivated, but when we activate TagManager, it seems to add a dependency on the plugin. Could this behaviour be avoided?

**Comment by snake14** [comment]
Hi @mikkeschiren . I'm sorry that you're experiencing this issue. I think that we're going to need a bit more information. I tested in my local Matomo install and was able to disable the Overlay plugin and enable the TagManager plugin without any issues. I also didn't see any reference to the overlay plugin in the TagManager code. I tested with Matomo 4.15.1; what version of Matomo are you using? What exactly are you seeing to make you say that TagManager is adding a dependency on the Overlay plugin?

**Comment by mikkeschiren** [comment]
Hi - sorry for not replying - will post steps to reproduce.

**Comment by AltamashShaikh** [comment]
@mikkeschiren Any update ?

**Comment by mikkeschiren** [comment]
Sorry, I am closing this now. If, when I have time to debug again, I can see it's TagManager causing the behaviour, I create a new issue. Sorry for this.

**Comment by mikkeschiren** [comment]
Just a note, this was the cause: https://github.com/matomo-org/matomo/issues/21891
