### ISSUE TITLE
Hugo Alberto Rada Hernández 

### ISSUE THREAD

**Issue by RadaHugo7** [matomo-org/tag-manager#704]
https://github.com/Huawei/Huawei_LiteOS_Kernel/commit/a254524da24dd8f9984e83fbce0b33dca5016a13

**Comment by snake14** [comment]
Hi @RadaHugo7 . It looks like there was an complication in posting your issue. I don't see any description. I'm going to close this issue, but please feel free to comment or open a new issue. If you haven't already, please check out [Matomo's knowledge base](https://forum.matomo.org/).
