### ISSUE TITLE
[Bug] Tag Manager link not working

### ISSUE THREAD

**Issue by bojana-z** [matomo-org/tag-manager#724]
When I click on 'Create a container now' from the getting started page ("How do I get started" section) in Tag Manager on Cloud, I encounter this error “**Action 'manageContainers}' not found in the module 'TagManager'**“

![image](https://github.com/matomo-org/tag-manager/assets/146905988/f5221eae-e742-4429-b8ff-ac87d17afa0a)

**Comment by snake14** [comment]
Hi @bojana-z . Thank you for creating this issue. I have just merged the fix, which should be included in the next Matomo 5 release.
