### ISSUE TITLE
Version name Character Limit error

### ISSUE THREAD

**Issue by goochj03** [matomo-org/tag-manager#727]
When trying to publish a certain Tag Manager container I get the error message Name: The value contains "55" characters but should contain at most 50 characters despite the Name field containing a few characters. See images below.

![taglimit](https://github.com/matomo-org/tag-manager/assets/118518962/dc85a24a-838b-4a9f-809d-e372e0243532)

The error shown in the browser console window (Instance name hidden):
![tag-error](https://github.com/matomo-org/tag-manager/assets/118518962/9e8ba5ec-e1f5-4084-9099-c2bdcd3947c5)

**Comment by AltamashShaikh** [comment]
@goochj03 I just tried publishing the container with the above values and it seems to work for me, can you share more info about your instance and version you are using ?

**Comment by AltamashShaikh** [comment]
This issue occurred due to 1 variable with name `CSS Variable - top-mobile-icons text "log in"` and on publish the API calls were escaping the quotes and which lead the name to `CSS Variable - top-mobile-icons text &quot;log in&quot;` and caused this issue, this issue is for tags and triggers too
