### ISSUE TITLE
Only debug mode works

### ISSUE THREAD

**Issue by everleazy** [matomo-org/tag-manager#734]
Hello!

We use Matomo Tag Manager.

I created tags and triggers, they work fine in debug mode.
But without debugging mode nothing works.

Changes are published live.
The publication proceeds without any errors.

**Comment by AltamashShaikh** [comment]
@everleazy do you have any url where we can check this?

**Comment by everleazy** [comment]
> @everleazy do you have any url where we can check this?

Yes, sure.)
https://edgeam.am/

**Comment by snake14** [comment]
Hi @everleazy . Thank you for sharing your URL. I can see that the container JS is loading, but I don't see the Matomo JS loading. Do you happen to have the following setting unchecked in your Matomo configuration variable?
![Screenshot from 2023-12-13 08-57-12](https://github.com/matomo-org/tag-manager/assets/11394099/5a173dd6-50d4-40ec-a78e-6b20b3c26db2)

**Comment by snake14** [comment]
Hi @everleazy . I just wanted to check in and see if you were still experiencing this problem or if we're good to close this issue?

**Comment by AltamashShaikh** [comment]
@everleazy Closing this issue, please feel free to reopen if you are still facing the issue.
