### ISSUE TITLE
[Bug] Unable to use "Publish a new version now" when changing tags or triggers

### ISSUE THREAD

**Issue by Starker3** [matomo-org/tag-manager#740]
When updating a variable, tag or trigger the button to "Publish a new version now" returns an error `Please specify a value for 'idContainer'.`

Clicking the "Publish" button on the left menu works as normal.

This seems to only be happening since updating to 5.0.0

![image](https://github.com/matomo-org/tag-manager/assets/20905821/f31f51a7-a670-4655-b0b1-1355da75b853)
![image](https://github.com/matomo-org/tag-manager/assets/20905821/fb635f6e-e9f1-41ce-8829-2362e0994b76)

**Comment by snake14** [comment]
Thank you for creating this issue @Starker3 . I was able to reproduce in my local environment. It looks like the `TagManager.getContainerVersions` API call is leaving the `idContainer` value empty for some reason.

**Comment by snake14** [comment]
The fix for the issue will be included in the next Matomo release, so probably 5.0.1.
