### ISSUE TITLE
[Bug]Error in Matomo Tag Manager Debug Mode

### ISSUE THREAD

**Issue by ghost** [matomo-org/tag-manager#744]
### What happened?

After following the provided instructions on integrating Matomo Analytics tracking code via the Matomo Tag Manager for a React-based website, encountering an error during the preview/debug mode. The specific error message received is: "Error while logging event: Parameters category and action must not be empty or filled with whitespaces."

### What should happen?

The Matomo Tag Manager should not throw an error related to empty or whitespace-filled parameters when firing a trigger in the preview/debug mode.

### How can this be reproduced?

   1. Followed the provided instructions(https://matomo.org/faq/new-to-piwik/how-do-i-start-tracking-data-with-matomo-on-websites-that-use-react/) for setting up Matomo Analytics tracking code via the Matomo Tag Manager on a React website.
    2. Created triggers and tags in Matomo Tag Manager based on the provided guidelines.
    3. Integrated the Matomo Tag Manager JS code into the React application using the recommended method.
    4. Fired a trigger in the preview/debug mode.
    6. Observed the error message in the console: "Error while logging event: Parameters category and action must not be empty or filled with whitespaces."

### Matomo version

5.0.1

### Server operating system

localhost

### What browsers are you seeing the problem on?

Chrome

### Computer operating system

Windows 11

### Validations

- [X] Read our [Contributing Guidelines](https://github.com/matomo-org/matomo/blob/5.x-dev/CONTRIBUTING.md).
- [X] Follow our [Security Policy](https://github.com/matomo-org/matomo/blob/5.x-dev/SECURITY.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
- [X] The provided steps to reproduce is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the Bug.

**Comment by snake14** [comment]
Hi @MariyanK1 . I'm sorry to hear that you're experiencing this issue. It sounds like a tracking request is being sent with empty parameters for some reason. I'm not really sure what would cause that. Have you tried narrowing down if it's a specific trigger or tag that's causing the issue?

I was unable to reproduce with my local 5.0.1 instance, but I don't have a working React page and it might be specific to that type of setup. @AltamashShaikh Do you have a test React page that you could try reproducing the issue with?

**Comment by ghost** [comment]
> Hi @MariyanK1 . I'm sorry to hear that you're experiencing this issue. It sounds like a tracking request is being sent with empty parameters for some reason. I'm not really sure what would cause that. Have you tried narrowing down if it's a specific trigger or tag that's causing the issue?
> 
> I was unable to reproduce with my local 5.0.1 instance, but I don't have a working React page and it might be specific to that type of setup. @AltamashShaikh Do you have a test React page that you could try reproducing the issue with?

Thank you for the reply. I will send you more info about my predicament tomorrow because here in Bulgaria it is close to midnight.

**Comment by AltamashShaikh** [comment]
@snake14 @MariyanK1 Followed the steps and it works fine for me without any error, @MariyanK1 Did you create additional tags to track events in Matomo maybe ?

**Comment by ghost** [comment]
Thank you, @AltamashShaikh. That was the problem. To be fair it's kind of a cryptic error for a simple missed tag. Whatever I considered the matter resolved. Keep up the good work!
