### ISSUE TITLE
Sometimes idsite=''

### ISSUE THREAD

**Issue by webian** [matomo-org/tag-manager#751]
Using MTM with a Matomo Analytics tag that gets the config from a var `Matomo Configuration` that gets Matomo idSite from a datalayer variable `siteID` so I can use the sama container for different sites.

It works most of the time so it's not a configuration issue.

But sometimes I get a php error "**Error in Matomo (tracker): Invalid idSite: '0'**" thrown here: https://github.com/matomo-org/matomo/blob/b58a33309e86358a99083f34abfd543c76c6e80b/core/Tracker/Request.php#L611

I temporarily edited that line adding `json_encode($this->params)` and I see from the log that idsite is an empty string (`"idsite":""`).

So, if I'm not wrong, it's MTM that sometimes is unable to pass the right value of idsite. Maybe is some kind of sync/timing issue in the MTM creation of the request to log the event in Matomo?

**Comment by AltamashShaikh** [comment]
@webian Looks like the dataLayer might be setting the idSite value after the container.js is loaded, can you maybe ensure to load the container.js after the idsite is added via dataLayer ?

**Comment by webian** [comment]
The problem is sporadic so I'm sure it's not a configuration problem because most of the time the visits are recorded without problem.

I added more info to Request.php and I found that the requests causing the problem come from Bytedance spider with this user agent:
`Mozilla/5.0 (Linux; Android 5.0) AppleWebKit/537.36 (KHTML, like Gecko) Mobile Safari/537.36 (compatible; Bytespider; [spider-feedback@bytedance.com](mailto:spider-feedback@bytedance.com))`

**Comment by webian** [comment]
I also add that I did setup the default value of datalayer variable `siteID` to 99999 (inexistent website) but the logged error states: `Error in Matomo (tracker): Invalid idSite: '0'`. Shouldn't it be 99999 instead of 0 since in this cases `$this->params['idsite']=''`?

**Comment by AltamashShaikh** [comment]
@webian Hard to comment what could be the actual cause, I tried reproducing this one by creating a Matomo configuration where idSite is determined via dataLayer variable and the default value is set, it seems to work fine for me. Do you have any url where we can see the implementation ?

**Comment by webian** [comment]
You can check my website for example: https://www.webian.it/

Btw, as I said, the problematic requests come from a spider so, to reproduce the error, one should first make the request as the spider does.

**Comment by AltamashShaikh** [comment]
@webian Cannot find any issue, may be the `bytedance` bots not recognising CDATA content properly?

try setting `mtm_push` after line 75 ?
![Screenshot from 2024-01-31 13-47-48](https://github.com/matomo-org/tag-manager/assets/14902277/f17e2886-07c6-4728-b603-9f0f5b10afae)

**Comment by AltamashShaikh** [comment]
@webian any luck after making the recommended changes ?

**Comment by webian** [comment]
> try setting `mtm_push` after line 75 ?

@AltamashShaikh what do you mean here?

**Comment by AltamashShaikh** [comment]
@webian I meant implementing the code in following way
```
<!-- Matomo Tag Manager Common -->
<script>
  window._mtm = window._mtm || [];
  window._mtm.push({
   'matomoSiteID': '2',
   'matomoURL': 'https://mat.webian.it/',
   'pageType': 'homepage'
  });
  window._mtm.push({'mtm.startTime': (new Date().getTime()), 'event': 'mtm.Start'});
  (function() {
    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
    g.async=true; g.src='https://mat.webian.it/js/container_FuppaPKk.js'; s.parentNode.insertBefore(g,s);
  })();
</script>
<!-- End Matomo Tag Manager Common -->
```

**Comment by webian** [comment]
@AltamashShaikh ok, I just pushed the change and will monitor in the next days and report back...

**Comment by webian** [comment]
Sorry but the problem persists.

I received 2 other php errors "Error in Matomo (tracker): Invalid idSite: '0'" with requests from `Mozilla/5.0 (Linux; Android 5.0) AppleWebKit/537.36 (KHTML, like Gecko) Mobile Safari/537.36 (compatible; Bytespider; [spider-feedback@bytedance.com](mailto:spider-feedback@bytedance.com))`

**Comment by snake14** [comment]
@webian Is the issue is only happening with Bytespider? Cause that [appears to be a web crawler](https://darkvisitors.com/agents/bytespider). You might want to block it, using your robots.txt, as that article suggests.

**Comment by webian** [comment]
Closed as completed?

**Comment by AltamashShaikh** [comment]
@webian Updated the status to "not planned" we won't be working on this, if you want to block the requests for the above spider, you can try using [TrackingSpamPrevention](https://github.com/matomo-org/plugin-TrackingSpamPrevention) plugin

**Comment by webian** [comment]
@AltamashShaikh I am already using that plugin. It has no effect on the problem.

In fact, the requests causing the problem are not spam, but come from Bytespider, a web crawler run by ByteDance, the owner of TikTok.

IMHO, the right way to handle this problem is not to block the requests, but to reproduce the request to trigger the Matomo bug. I unfortunately could not reproduce the exact HTTP request from the crawler.

BTW, closing a bug report in this way is a bit like sweeping the dust under the rug. Nothing serious in this case. But the approach could be better.

**Comment by AltamashShaikh** [comment]
@webian We did tried reproducing and didn't find much success as you did, If you could provide us the exact steps to reproduce it, we can definitely think of adding a fix or finding a way to prevent the issue, unless that is not provided we can't do much here.

We can re-open the issue if anyone has the steps to reproduce this bug
