### ISSUE TITLE
UX : Enhancement: Redirect to List Page After Creating Tags/Triggers/Variables

### ISSUE THREAD

**Issue by Chardonneaur** [matomo-org/tag-manager#764]
## Issue Description

Currently, in Matomo Tag Manager (MTM), when a user creates a tag, trigger, or variable, they are greeted with a confirmation message indicating that the creation process is underway. While this confirmation is useful, it could be significantly more user-friendly and efficient if, after creation, the user is automatically redirected to the respective list page (tags, triggers, variables). This redirection would not only confirm the successful creation of the item but also streamline the process of creating additional items by providing immediate access to the list page.

## Suggested Enhancement

**Automatic Redirection Post-Creation**: After a user successfully creates a tag, trigger, or variable, the system should automatically redirect them to the corresponding list page (e.g., the list of all tags after creating a new tag). This would offer a visual confirmation that the item has been added and facilitate the creation of new items by providing direct access to the "Add New" action or button from the list page.

**Comment by snake14** [comment]
Hi @Chardonneaur . Thank you for this enhancement suggestion. I am marking it to be reviewed and prioritised by our Product team.

**Comment by Stan-vw** [comment]
We'll need to assess if this makes sense, as automatically redirecting people has downsides too

**Comment by Chardonneaur** [comment]
Hello, 
@snake14 @Stan-vw 
I am sorry, I am a bit lost here, this ticket is written as completed, but I am not sure. Does it mean that this feature has already been developed and ready to be pushed?

**Comment by Stan-vw** [comment]
It's merged and just waiting for the next core release 👍
