### ISSUE TITLE
Add a checkbox within the Matomo configuration variable to track bots

### ISSUE THREAD

**Issue by Chardonneaur** [matomo-org/tag-manager#771]
Hi team,
That's really a minor thing, but adding a checkbox with the following feature "_paq.push(['appendToTrackingUrl', 'bots=1']);." within the Matomo configuration variable will allow us to easily track bots with Matomo Tag Manager.

**Comment by snake14** [comment]
Hi @Chardonneaur . Thank you for taking the time to create this issue. I agree that would be a fairly easy implementation. Do you have any guess as to how many customers would be interested in that option?

**Comment by Chardonneaur** [comment]
@snake14 to be honest, almost no one, it is a very very low priority issue. I just wanted to docment it. It could only have value if we had an extensive documentation explaining the benefits of bot tracking.

**Comment by Stan-vw** [comment]
would you say the feature adds more value than the downside of adding the extra complexity? (additional tickbox, additional helptext, it's all overhead to the users)

**Comment by Chardonneaur** [comment]
I think we could group all the optionnal settings into a drop down menu.
But I am saying also that the tag manager should reflect the capabilities of Matomo, so not offering this feature is a drawback to me.

**Comment by kartzke** [comment]
+1 for this request
