### ISSUE TITLE
Add a Conversion ID Field to MTM Linkedin Tags

### ISSUE THREAD

**Issue by 9joshua** [matomo-org/tag-manager#776]
The Matomo Tag Manager Linkedin Tag provides only the ability to add a Partner ID.

Adding an optional Conversion ID would make it possible to track specific conversions with this Tag. The optional field could also accept variables to make conversion tracking dynamic.

**Comment by snake14** [comment]
Hi @9joshua . Thank you for taking the time to create this issue. I'm not familiar with that specific integration, but that sounds like a reasonable enhancement. I'm marking this issue to be reviewed and prioritised by our Product team.

**Comment by 9joshua** [comment]
@snake14 Closing this as per your feedback on another channel the conversion ID is not directly tied to the insight tag and can be configured and sent in another call via a Custom HTML Tag.

**Comment by snake14** [comment]
@9joshua Sorry for the confusion. After I messaged you that we shouldn't implement it, I thought of a way to make it work. So, I went ahead and added it. The new field should be available in the next core release.
