### ISSUE TITLE
[Enhancement] Add Custom Dimension tracking as an option for Matomo Analytics Tags

### ISSUE THREAD

**Issue by 9joshua** [matomo-org/tag-manager#806]
The only way to track Custom Dimensions on demand via the Matomo Tag Manager is to use a Custom HTML Tag. The default Custom Dimension field in the Matomo Configuration Variable is not suitable/practical for setting trigger-based Custom Dimensions.

We should be able to add Custom Dimension tracking as a 'Tracking Type' option for Matomo Analytics Tags. For example...
![image](https://github.com/matomo-org/tag-manager/assets/20234985/e5891988-90a7-44bc-ae40-194d30f5284e)

The options for this tracking type would be Custom Dimension ID and value - where the value can accept a variable.

**Comment by AltamashShaikh** [comment]
@9joshua We already have this option available with Matomo Configuration variable to set the custom dimensions, do you mean having an additional tag which will have similar UI to set the custom dimensions ? 

![Screenshot from 2024-06-24 07-17-02](https://github.com/matomo-org/tag-manager/assets/14902277/4e1894ba-3616-4a74-9972-308a986bafa6)

**Comment by 9joshua** [comment]
@AltamashShaikh Yes, I think it would be good to have a Custom Dimension that can be tied to a trigger - for example, if a visitor views a certain subset of pages or clicks a contact button. 

The Custom Dimension option in the Matomo Configuration Variable cannot be tied to a specific trigger and is more or less hard-coded for every visitor.

**Comment by chopsol** [comment]
I support this issue. Dimensions at the configuration level are bound to all Pageviews as well as to all Events. This leads to problematic evaluations, since events appear with action dimensions, although you may only need these dimensions for a page view. A single assignment of a Dimension values on Pageview and a different on Events would be very helpful. 
In contrast to the first screenshot of @9joshua, I would recommend the Dimensions as a supplement for a page view or an event. The integration should be identical as in the case of the configuration.

**Comment by AltamashShaikh** [comment]
@9joshua @chopsol I have marked this issue "for prioritisation", our product team will check and schedule this accordingly.

@chopsol You mean having the option to set custom dimensions in Matomo pageview/EventTag right ??

**Comment by chopsol** [comment]
@AltamashShaikh correct. Like this:
![tag-dimension](https://github.com/matomo-org/tag-manager/assets/12293848/d7c22b53-a59b-4b9f-b212-8599f74bf9ea)

**Comment by snake14** [comment]
We are having some discussion about how the newly defined custom dimensions on a tag should be applied. Here are the options that we discussed:
1. Apply to all tracking requests after the tag is triggered
2. Only the tracking request for the triggered tag
3. Have an additional tag setting providing the option to decide between 1 or 2

I'm leaning toward option 3, but thought we'd put it out to the community to see if there were any hard opinions.

**Comment by snake14** [comment]
@9joshua The PR has been merged. So, the ability to define custom dimensions for a Matomo tag should be available as part of the next Matomo release.
