### ISSUE TITLE
Matomo Tag Manager Working in Preview Mode but Not Firing After Publication

### ISSUE THREAD

**Issue by Chardonneaur** [matomo-org/tag-manager#811]
## Description

I am experiencing an issue with Matomo Tag Manager where tags work correctly in preview mode but fail to fire once published. The detailed steps and environment information are provided below.

## Steps to Reproduce

1. Create a tag within Matomo Tag Manager.
2. Test the tag in preview mode, where it works as expected.
3. Publish the tag.
4. Observe that the tag does not fire on the live site.

## Expected Behavior

The tags should fire on the live site after being published, just as they do in preview mode.

## Current Behavior

The tags only work in preview mode and do not fire after publication.

## Environment

- Matomo version: 3.14.1 (And unfortunately, I cannot update it !!!!!)
- Browser: Chrome / Internet Explorer
- OS: Windows 11

## Additional Information

- I have cleared all caches and tried accessing the site in incognito mode to ensure there are no caching issues.
- The site is self-hosted, intranet analytics.

Any help resolving this issue would be greatly appreciated. Thank you!

**Comment by AltamashShaikh** [comment]
@Chardonneaur I checked this one and it seems to be working for me for Matomo 3.14.1

Can you check if you are publishing the changes correctly ? I mean there are 2 buttons. Please use the 2nd button "Create new version and publish release"

![Screenshot from 2024-06-28 08-42-34](https://github.com/matomo-org/tag-manager/assets/14902277/3498be00-69a6-4cb1-a1d8-8ac9ffe4010b)

**Comment by Stan-vw** [comment]
As per our long term support guidelines (https://matomo.org/blog/2016/01/announcing-long-term-support-in-matomo-the-analytics-platform-for-your-mission-critical-projects/), Matomo 3.X is no longer supported.
I'm closing this ticket, but please reopen it in case you have this issue on Matomo 5.X.
