### ISSUE TITLE
UX - Add an icon to copy/paste the Matomo Tag Manager container

### ISSUE THREAD

**Issue by Chardonneaur** [matomo-org/tag-manager#812]
Hi Team,

Here is a quick video explaining what would improve easily the UX of Matomo Tag Manager by adding an icon to copy/paste easily the container of Matomo Tag Manager:

https://github.com/matomo-org/tag-manager/assets/28002238/66da5bea-7467-45de-b702-3e6efafe71e1

**Comment by AltamashShaikh** [comment]
@Chardonneaur Thanks for opening this issue, we already have this scheduled in current sprint :)
