### ISSUE TITLE
Increase the limit of characters displayed for the description

### ISSUE THREAD

**Issue by ronan-hello** [matomo-org/tag-manager#815]
Actually, the description field (for tags, triggers and variables) don't display the entire description.

![Capture d'écran 2024-07-03 151014](https://github.com/matomo-org/tag-manager/assets/24936187/1e53fac5-7a0b-43f9-8f13-57e2d71509cb)

As you can see, only few letters are displayed instead of a clear description.

**Comment by snake14** [comment]
Hi @ronan-hello . Thank you for taking the time to create this issue. It looks like the name is given preference, which makes sense. You can also see the full description if you hover your cursor over the truncated text. We can look into whether there's a better way to present this.

@Stan-vw This seems like a potential enhancement to look into as part of our current focus.

**Comment by Stan-vw** [comment]
Thanks @ronan-hello , we'll have a look at this. Can you let us know: do you ever use breaklines in your descriptions, or just 1 line descriptions?
We're considering making the description field a shorter field just to clean up the tag/trigger/variable config screen, but I don't have enough input from users yet whether this would be fine or potentially annoying. Thanks for letting me know what you think 👍 

cc @Javi-Ormaechea

**Comment by ronan-hello** [comment]
Hi everyone,

Thank you for your replies.
Some customers ask me to write a description for their tag to be able to maintain their configuration.
I usually don't write long description (without any line breaks). But I think that you can handle this feature.
For example, some customers may have a list in their tag/trigger description to explain different cases.

The description may be in a collapsing section, or under the title (currently side by side) but the first few lines should be visible without any action. I know that you have to full description with html `title` attribute right now, but it's not very useful when user is a beginner and have to find the right tag.

Hope this could help
Regards
Ronan HELLO
