### ISSUE TITLE
Increase tags and triggers title length

### ISSUE THREAD

**Issue by ronan-hello** [matomo-org/tag-manager#816]
Hi,

Actually, the tags and triggers title field is limited to only 50 characters.
Can you increase this limit to 255 characters ? It would be a great improvement and allow users to follow naming guideline such as :

Matomo - Event - my_custom_event_name_even_if_the_name_is_long

We actually can't name a tag with a long name, and it'll force users to change the naming convention or change event name to shorts (which can cause confusion).

Regards,
Ronan HELLO

**Comment by snake14** [comment]
Hi @ronan-hello . Thank you for taking the time to create this issue. You make a good point. Even increasing the allowed length to 100 characters would allow more unique names. We'd need to confirm that increasing the length of the name wouldn't have any negative side-effects. It would complicate displaying the full name in the UI. We hash tag names in the container JavaScript, so we wouldn't be increasing the size of that file.

@Stan-vw This might be a good enhancement to look at as part of our current focus.

**Comment by Stan-vw** [comment]
Thanks, that seems like a great little improvement! We'll schedule some time to check if it breaks anything, otherwise we can likely fix this shortly

**Comment by ronan-hello** [comment]
Hello everyone,

OK, I understand the situation about hashing the title and display.
Glad to see this can be fixed soon !

Regards,
Ronan HELLO

**Comment by snake14** [comment]
Hi @ronan-hello . I have just merged the PR. So, the changes should be included with the next Matomo release.
