### ISSUE TITLE
Bug - If a website is using non latin caracters within its urls then the page url trigger does not work

### ISSUE THREAD

**Issue by Chardonneaur** [matomo-org/tag-manager#828]
Hi Team,

If you take the following web page:
![Screenshot from 2024-07-17 11-42-08](https://github.com/user-attachments/assets/c574b7cf-22fe-41ee-af21-3d4fb353a4ea)
using those Chinese caracters as a page url trigger won't work.

**Comment by AltamashShaikh** [comment]
@Chardonneaur Can you paste the URL here ?

**Comment by Chardonneaur** [comment]
@AltamashShaikh well it is getting encoded like this https://www.neugart.com/zh-cn/%E6%9C%8D%E5%8A%A1/%E4%BC%98%E8%B4%A8%E5%94%AE%E5%89%8D%E5%92%A8%E8%AF%A2

**Comment by AltamashShaikh** [comment]
@Chardonneaur Does it work if you enter `https://www.neugart.com/zh-cn/%E6%9C%8D%E5%8A%A1/%E4%BC%98%E8%B4%A8%E5%94%AE%E5%89%8D%E5%92%A8%E8%AF%A2` instead of the actual URL ??

![Screenshot from 2024-07-18 09-44-53](https://github.com/user-attachments/assets/ff3bdb80-ae71-4d38-b35b-6de18eb64fc0)

**Comment by Chardonneaur** [comment]
Yes it does

**Comment by Chardonneaur** [comment]
So, I guess, one workaround should be to have an FAQ or an information message about it no? @AltamashShaikh

**Comment by AltamashShaikh** [comment]
@Chardonneaur Yes we should have an FAQ around it, so that people doesn't face similar problem, as copying the URL from browser always gives the encoded URL, so it should be good to fix it via an FAQ, else people copying the URL from browser will face the similar issue.

**Comment by Chardonneaur** [comment]
Ok, so I am creating a ticket about it.
