### ISSUE TITLE
Create Server-Side Matomo Tag Manager

### ISSUE THREAD

**Issue by Chardonneaur** [matomo-org/tag-manager#875]
Hi team,

One recurrent request that we have for Matomo Tag Manager is "Is there a server-side version of Matomo Tag Manager?" As the answer is no, I am creating this ticket here in order to keep a record of this demand.

**Comment by snake14** [comment]
Hi @Chardonneaur . Thank you for taking the time to create this issue. It appears to be a duplicate of #305 . I'll close this issue in favour of that one.
