### ISSUE TITLE
Add new tag: Verify your site ownership

### ISSUE THREAD

**Issue by tsteur** [matomo-org/tag-manager#89]
Helps you verify site ownership for Google see https://support.google.com/webmasters/answer/35179?hl=en 
eg by adding a meta `<meta name="google-site-verification" content="String_we_ask_for">`

(to be tested if GA executes the JS of the container and recognizes it)

**Comment by Findus23** [comment]
I'd be really surprised if the verification crawler did anything more than fetch the HTML, but it's worth a try.

**Comment by tsteur** [comment]
It says you can verify with "Google Tag Manager container snippet" on that page. So hoping it'll work for us as well.

**Comment by tsteur** [comment]
Might only support GTM though.

**Comment by Findus23** [comment]
I checked again and it really seems like they just searched the HTML for the noscript GTM container code.
https://www.analyticsmania.com/post/solved-cannot-verify-google-search-console-with-google-tag-manager/

**Comment by tsteur** [comment]
👍  will close
