### ISSUE TITLE
Remove hidden limitation on Container Publish Capability

### ISSUE THREAD

**Issue by Stan-vw** [matomo-org/tag-manager#893]
When I looked at the MTM permission system (under System>User>Capabilities), the attached combination of user permissions is what I expected between the "Use Custom Templates capability" and "Publish Live Container capability":
![image](https://github.com/user-attachments/assets/1ec7f287-43c6-4e1b-93a9-d537d395fca3)

However this is not the case. Currently, the bottom left square also has the hidden limitation
> But cannot publish a container with custom templates

That means that the Publish button does not show up for users with Publish Live Container capability when someone has added/updated a custom tag/trigger/variable in the container. For them, the navbar shows up as:
![image](https://github.com/user-attachments/assets/a090bbb2-859b-43d2-b987-7129673656bf)

Suggested change: remove this hidden limitation to align the actual capabilities with the wording of the capabilities.
Note: this does mean that users with Publish Live Container capability now are responsible for the quality of the custom templates that go live. This aligns with a RACI matrix where the approver isn't always the one that is allowed to create the object that gets approved.

**Comment by atom-box** [comment]
This sounds great to me. 
(I contacted now the person who raised this concern. I will soon post here or they will post further thoughts.)

**Comment by atom-box** [comment]
The person who raised this has replied: 

> Thank you very much for your answer. The proposed change is fine for me.

**Comment by AltamashShaikh** [comment]
This should be updated with a new core release.
