### ISSUE TITLE
Tag Manager: CORS error when using preview/debug mode

### ISSUE THREAD

**Issue by 9joshua** [matomo-org/tag-manager#902]
## Context:

When using the MTM preview/debug feature Matomo calls to the reporting API (index.php) to gather data (not really sure if this call is needed as it requires a Token Auth)…

https://example.matomo.cloud/?module=API&format=json&method=Cloud.logVisits&urlModule=&urlAction=&urlCategory=&urlSubCategory=&segment=&date=

## Problem:

With prior versions either this call was not made or handled differently. Now the browser rejects the API response because it is not served with CORS headers…
![Screenshot from 2024-10-04 11-32-23](https://github.com/user-attachments/assets/a8f96210-195f-4f72-9df2-0a797426d9ae)

Even if the browser did accept the response it would likely be a 401 response…
![Screenshot from 2024-10-04 11-36-04](https://github.com/user-attachments/assets/85ccf731-b5a1-4610-a1b0-34f298c108f6)

I have reproduced this with 2 other Cloud customers.

This issue is not present on my OP instance running Matomo Version 5.1.2. I do not see the associated API request when using preview mode with this instance.

## Solution:

- Remove this call if it is not needed, OR

- Handle the request/response differently

**Comment by snake14** [comment]
Hi @9joshua . Thank you for taking the time to create this issue and providing good background information and screenshots. That API call definitely appears to be specific to the Matomo Cloud environment. As far as I can tell, it's coming from `plugins/Cloud/javascripts/trackDashboardVisits.js`. @AltamashShaikh Is there something that we need to do to prevent that API call from being sent by the MTM preview pane?

Edit: I was able to reproduce the issue using altamash.matomo.cloud. It appears that the Cloud specific JS is loaded by the mtmDebugFrame as part of the `index.php?module=Proxy&action=getNonCoreJs` request. I wonder if we should pass an extra query parameter with that request to prevent `trackDashboardVisits.js` from being included.

**Comment by AltamashShaikh** [comment]
@snake14 @9joshua Its a regression due to a recent change in Cloud plugin, we need to make changes there and no issue in plugin.
Will update internally

**Comment by AltamashShaikh** [comment]
FYI, This should be fixed in next Matomo cloud deployment, probably by Wednesday (23rd Oct 2024).
