### ISSUE TITLE
Cache issue when editing a trigger

### ISSUE THREAD

**Issue by Chardonneaur** [matomo-org/tag-manager#903]
Hi Team,

When we edit a trigger, there is a cache issue which is making the end users really confused.
To reproduce it, open a trigger at the level of a tag, edit the trigger, then come back within the trigger, and you will see that the edit has not been taken into consideration.
The solution is to remove the cache.
Everything is explained within this video:

https://github.com/user-attachments/assets/1be83426-8b6a-49c5-b9cc-04d6ca68c8e7

**Comment by Stan-vw** [comment]
Thanks for adding the video, adds great clarity 👍
