### ISSUE TITLE
Add new tag: Drift chat

### ISSUE THREAD

**Issue by tsteur** [matomo-org/tag-manager#91]
see https://help.drift.com/article/how-to-setup-drift-in-google-tag-manager/

**Comment by Findus23** [comment]
As the docs keep it a secret, this is their tracking code that you get during signup:
```html
<!-- Start of Async Drift Code -->
<script>
"use strict";

!function() {
  var t = window.driftt = window.drift = window.driftt || [];
  if (!t.init) {
    if (t.invoked) return void (window.console && console.error && console.error("Drift snippet included twice."));
    t.invoked = !0, t.methods = [ "identify", "config", "track", "reset", "debug", "show", "ping", "page", "hide", "off", "on" ], 
    t.factory = function(e) {
      return function() {
        var n = Array.prototype.slice.call(arguments);
        return n.unshift(e), t.push(n), t;
      };
    }, t.methods.forEach(function(e) {
      t[e] = t.factory(e);
    }), t.load = function(t) {
      var e = 3e5, n = Math.ceil(new Date() / e) * e, o = document.createElement("script");
      o.type = "text/javascript", o.async = !0, o.crossorigin = "anonymous", o.src = "https://js.driftt.com/include/" + n + "/" + t + ".js";
      var i = document.getElementsByTagName("script")[0];
      i.parentNode.insertBefore(o, i);
    };
  }
}();
drift.SNIPPET_VERSION = '0.3.1';
drift.load('WHAT_I_ASSUME_IS_THE_APPID');
</script>
<!-- End of Async Drift Code -->
```

**Comment by tsteur** [comment]
cheers @Findus23

**Comment by Danmasani12** [comment]
pls can u explain how this code works its urgently needed

**Comment by Danmasani12** [comment]
please can you explain how this code works

**Comment by AltamashShaikh** [comment]
@Danmasani12 Do you want to know the working of Drift tag or how to add drift tag via Matomo tag manager ?
If you want to add a Drift tag via Matomo Tag Manager you can do so by creating a new tag and select Drift tag under social and configure the tag as per your need

![Screenshot from 2023-01-19 17-54-46](https://user-images.githubusercontent.com/14902277/213442470-fa988bec-2110-484e-adfb-110258d34bd1.png)

![Screenshot from 2023-01-19 17-55-50](https://user-images.githubusercontent.com/14902277/213442585-b0a16665-cb9c-4297-b38d-f395054e2bdf.png)
