### ISSUE TITLE
Turn off spellcheck in CustomHTML tag textarea

### ISSUE THREAD

**Issue by ronan-hello** [matomo-org/tag-manager#926]
Hi,

Can you add `spellcheck="false"` to the "Custom HTML" tag `<textarea>` to disable spellcheck for code input?

Current tag:
```
<textarea
class="control_textarea materialize-textarea"
type="textarea"
id="customHtml"
name="customHtml"
placeholder=""
style="width: calc(100% - 40px);"
></textarea>
```

After modifications:
```
<textarea
class="control_textarea materialize-textarea"
type="textarea"
id="customHtml"
name="customHtml"
placeholder=""
style="width: calc(100% - 40px);"
spellcheck="false"
></textarea>

This will ensure top have a better user experience.

Regards,
Ronan HELLO

**Comment by randy-innocraft** [comment]
Hi @ronan-hello,
Thank you for bringing this to our attention and for your valuable input.
Your suggestion seems like a valuable enhancement to our product.
We will forward this to our Product team for review and future consideration.
If you have any additional details or questions, please feel free to share them here.

**Comment by ronan-hello** [comment]
Thank you for your interest in this issue!

Bests,
Ronan
