### ISSUE TITLE
console generate:tagmanager-tag (Not working)

### ISSUE THREAD

**Issue by scysys** [matomo-org/tag-manager#93]
Reference: https://developer.matomo.org/guides/tagmanager/custom-tag

Execute: ./console generate:tagmanager-tag

Ends up in

```
You have to enter the name of an existing plugin
```

<img width="314" alt="bildschirmfoto 2018-10-02 um 13 34 06" src="https://user-images.githubusercontent.com/1695531/46346289-d7c83500-c647-11e8-93fb-59a7c3401683.png">

**Comment by Findus23** [comment]
That's because you ` have to enter the name of an existing plugin`.

This means instead of entering random characters, enter the name of the plugin that is installed where you want to add the Tag. (In most cases this will be `TagManager`)

**Comment by scysys** [comment]
You have right, thanks.
