### ISSUE TITLE
Make a Copy-Paste button for the tracking code

### ISSUE THREAD

**Issue by atom-box** [matomo-org/tag-manager#930]
This entire story is just "add a button".

There should be a copy button, for the script block here:
Tag Manager >> Container >> "Install Code" 
![image](https://github.com/user-attachments/assets/875a87bc-b19d-48cf-b708-fa0ff53d0740)

The normal Matomo JS Tracker code already has such a copy button, here: 
Admin >> Measurables >> Tracking Code 
![image](https://github.com/user-attachments/assets/0e5b8f17-29c6-4b6a-bf51-791ccd62a4e0)

**Comment by snake14** [comment]
Hi @atom-box . Thank you for taking the time to create this issue. Were you testing with an on-premise install? I just checked Cloud and it appears that we've already added the requested copy button to MTM. So, it's available for Cloud customers and will be available for on-premise when customers upgrade to Matomo 5.2.0.

![image](https://github.com/user-attachments/assets/c468e079-6df3-4238-a3a3-f9aafeaa477d)
