### ISSUE TITLE
Individual Tag created - update installed - Individual Tag deleted

### ISSUE THREAD

**Issue by ben-dw** [matomo-org/tag-manager#94]
Hi there, 
we have created our own event tag for etracker. By running the latest update, the files were deleted and we had to install the tag again. Furthermore we have to set up the tags again, as it doesn't work anymore.

How can we avoid this?

**Comment by Findus23** [comment]
In case you want others to be able to use the tag, you can create a pull request here so it gets integrated in MTM. 
Otherwise the easiest way is to create a custom plugin and store your tag there:
https://developer.matomo.org/guides/getting-started-part-1

**Comment by tsteur** [comment]
You mean you created a Tag template basically?  As @Findus23 mentioned ideally you create a pull request for this Tag here so it will be included in the next release. Alternatively, you can create your own plugin. Let us know if you have any questions about contributing that Tag to the Tag Manager with a pull request.
