### ISSUE TITLE
Move Form Element Variable from Click Variables to Form Variables in Matomo Tag Manager

### ISSUE THREAD

**Issue by Chardonneaur** [matomo-org/tag-manager#952]
Hi team,

Steps to reproduce

- Open Matomo Tag Manager and create a new tag.
- Add a variable to it.
- Look for the "Form Element" variable under the list of available variables.

What I got:
- The "Form Element" variable is listed under Click Variables, which is misleading for users.

What I expected instead:
- The "Form Element" variable should be listed under Form Variables, as it is more relevant to form tracking rather than click tracking.

![WhatsApp Image 2024-12-13 at 10 32 00 (1)](https://github.com/user-attachments/assets/85155984-9c0f-4913-a533-d9f2cb3d2c5e)

**Comment by snake14** [comment]
@Chardonneaur I'm closing this issue as the PR has been merged and the fix will be included in the next Matomo core release.
