### ISSUE TITLE
Add Namespace Convention to Avoid Tag Name Conflicts Between Matomo Official Tags and Tag Manager Extended Community Plugin

### ISSUE THREAD

**Issue by Chardonneaur** [matomo-org/tag-manager#954]
Hi Team,

This is an important issue.

Steps to reproduce

- Have the last version of Matomo (5.2.0)
- Update the Tag Manager Extended community plugin (on-premise).
- Use the Axeptio community tag.

What I got:
- The Axeptio community tag, even though it is more recent than the offcial Axeptio Matomo Tag.

What I expected instead:
- A namespace convention should be implemented to avoid tag name conflicts, allowing both Matomo official tags and community plugin tags to coexist without overriding each other.

Who asked for it?
- Ronan Hello, developer of the tag manager extended community plugin

https://github.com/user-attachments/assets/5938679e-dde6-421b-a3bd-15d36697a96e

**Comment by Stan-vw** [comment]
Hmm, we thought about it with the first set of tags but probably forgot about it in the second set.
Keen to hear what naming convention you think makes sense, I haven't come up with a good name yet except for indeed the name of the vendor (which it currently is, and creates this issue)

**Comment by Stan-vw** [comment]
Thanks for the clear video. We're shipping a fix shortly.

**Comment by Chardonneaur** [comment]
Thank you.

**Comment by AltamashShaikh** [comment]
Adding a fix was more complicated in TagManager plugin, I have created a [PR](https://github.com/openmost/TagManagerExtended/pull/7) in TagManagerExtended plugin to filter out the newly created tags by TagManager plugin.

**Comment by Stan-vw** [comment]
@ronan-hello just following up on this: I understand it's working now, but let us know in case there's anything that's still going wrong. We appreciate the awesome work you're putting into MTM Extended.

**Comment by Stan-vw** [comment]
btw I've closed this because I believe the immediate issue of this ticket was "there's currently a tag that doesn't work", which was fixed.
However, we've created a new ticket for the "long term" fix for a better Namespace convention: https://github.com/matomo-org/tag-manager/issues/963

**Comment by ronan-hello** [comment]
Hi @Stan-vw, thank you so much!
Yes, this issue is now fixed 👍
