### ISSUE TITLE
Issue with missing array key at upgrade 

### ISSUE THREAD

**Issue by mikkeschiren** [matomo-org/tag-manager#959]
Issue posted in Matomo issue queue: https://github.com/matomo-org/matomo/issues/22856
Suggeested patch here: https://github.com/matomo-org/tag-manager/pull/958

**Comment by MatomoForumNotifications** [comment]
This issue has been mentioned on **Matomo forums**. There might be relevant details there:

https://forum.matomo.org/t/errror-after-update-to-matomo-5-2/61622/6

**Comment by snake14** [comment]
Hi @mikkeschiren . Thank you for taking the time to create this issue and especially for creating a PR :+1:
